

#if WAVE_MERGE
#define		ECDSA_ECC_BASE_ADDR									(0x50000)
#else
#define		ECDSA_ECC_BASE_ADDR									(0x40000)
#endif

#define		ECDSA_ECC_ENABLE_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0000)
#define		ECDSA_ECC_ENABLE_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0002)

#define		ECDSA_ECC_STAT_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0004)
#define		ECDSA_ECC_STAT_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0006)

#define		ECDSA_RANDOM_SEL_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0008)
#define		ECDSA_RANDOM_SEL_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x000A)

#define		ECDSA_SHA_GEN_VERIFY_INITIAL_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x000C)
#define		ECDSA_SHA_GEN_VERIFY_INITIAL_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x000E)

#define		ECDSA_ARITH_PRIME_NUM0_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0010)
#define		ECDSA_ARITH_PRIME_NUM0_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0012)

#define		ECDSA_ARITH_PRIME_NUM1_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0014)
#define		ECDSA_ARITH_PRIME_NUM1_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0016)

#define		ECDSA_ARITH_PRIME_NUM2_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0018)
#define		ECDSA_ARITH_PRIME_NUM2_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x001A)

#define		ECDSA_ARITH_PRIME_NUM3_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x001C)
#define		ECDSA_ARITH_PRIME_NUM3_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x001E)

#define		ECDSA_ARITH_PRIME_NUM4_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0020)
#define		ECDSA_ARITH_PRIME_NUM4_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0022)

#define		ECDSA_ARITH_PRIME_NUM5_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0024)
#define		ECDSA_ARITH_PRIME_NUM5_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0026)

#define		ECDSA_ARITH_PRIME_NUM6_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0028)
#define		ECDSA_ARITH_PRIME_NUM6_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x002A)

#define		ECDSA_ARITH_PRIME_NUM7_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x002C)
#define		ECDSA_ARITH_PRIME_NUM7_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x002E)

#define		ECDSA_ARITH_ORDER0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0030)
#define		ECDSA_ARITH_ORDER0_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0032)

#define		ECDSA_ARITH_ORDER1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0034)
#define		ECDSA_ARITH_ORDER1_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0036)

#define		ECDSA_ARITH_ORDER2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0038)
#define		ECDSA_ARITH_ORDER2_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x003A)

#define		ECDSA_ARITH_ORDER3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x003C)
#define		ECDSA_ARITH_ORDER3_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x003E)

#define		ECDSA_ARITH_ORDER4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0040)
#define		ECDSA_ARITH_ORDER4_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0042)

#define		ECDSA_ARITH_ORDER5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0044)
#define		ECDSA_ARITH_ORDER5_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0046)

#define		ECDSA_ARITH_ORDER6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0048)
#define		ECDSA_ARITH_ORDER6_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x004A)

#define		ECDSA_ARITH_ORDER7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x004C)
#define		ECDSA_ARITH_ORDER7_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x004E)

#define		ECDSA_ARITH_BASE_PX0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0050)
#define		ECDSA_ARITH_BASE_PX0_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0052)

#define		ECDSA_ARITH_BASE_PX1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0054)
#define		ECDSA_ARITH_BASE_PX1_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0056)

#define		ECDSA_ARITH_BASE_PX2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0058)
#define		ECDSA_ARITH_BASE_PX2_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x005A)

#define		ECDSA_ARITH_BASE_PX3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x005C)
#define		ECDSA_ARITH_BASE_PX3_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x005E)

#define		ECDSA_ARITH_BASE_PX4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0060)
#define		ECDSA_ARITH_BASE_PX4_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0062)

#define		ECDSA_ARITH_BASE_PX5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0064)
#define		ECDSA_ARITH_BASE_PX5_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0066)

#define		ECDSA_ARITH_BASE_PX6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0068)
#define		ECDSA_ARITH_BASE_PX6_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x006A)

#define		ECDSA_ARITH_BASE_PX7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x006C)
#define		ECDSA_ARITH_BASE_PX7_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x006E)

#define		ECDSA_ARITH_BASE_PY0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0070)
#define		ECDSA_ARITH_BASE_PY0_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0072)

#define		ECDSA_ARITH_BASE_PY1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0074)
#define		ECDSA_ARITH_BASE_PY1_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0076)

#define		ECDSA_ARITH_BASE_PY2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0078)
#define		ECDSA_ARITH_BASE_PY2_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x007A)

#define		ECDSA_ARITH_BASE_PY3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x007C)
#define		ECDSA_ARITH_BASE_PY3_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x007E)

#define		ECDSA_ARITH_BASE_PY4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0080)
#define		ECDSA_ARITH_BASE_PY4_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0082)

#define		ECDSA_ARITH_BASE_PY5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0084)
#define		ECDSA_ARITH_BASE_PY5_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0086)

#define		ECDSA_ARITH_BASE_PY6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0088)
#define		ECDSA_ARITH_BASE_PY6_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x008A)

#define		ECDSA_ARITH_BASE_PY7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x008C)
#define		ECDSA_ARITH_BASE_PY7_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x008E)

#define		ECDSA_PRIVATE_KEY0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0090)
#define		ECDSA_PRIVATE_KEY0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0092)

#define		ECDSA_PRIVATE_KEY1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0094)
#define		ECDSA_PRIVATE_KEY1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0096)

#define		ECDSA_PRIVATE_KEY2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0098)
#define		ECDSA_PRIVATE_KEY2_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x009A)

#define		ECDSA_PRIVATE_KEY3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x009C)
#define		ECDSA_PRIVATE_KEY3_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x009E)

#define		ECDSA_PRIVATE_KEY4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x00A0)
#define		ECDSA_PRIVATE_KEY4_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00A2)

#define		ECDSA_PRIVATE_KEY5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x00A4)
#define		ECDSA_PRIVATE_KEY5_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00A6)

#define		ECDSA_PRIVATE_KEY6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x00A8)
#define		ECDSA_PRIVATE_KEY6_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00AA)

#define		ECDSA_PRIVATE_KEY7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x00AC)
#define		ECDSA_PRIVATE_KEY7_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00AE)

#define		ECDSA_EQUATION_A0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00B0)
#define		ECDSA_EQUATION_A0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00B2)

#define		ECDSA_EQUATION_A1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00B4)
#define		ECDSA_EQUATION_A1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00B6)

#define		ECDSA_EQUATION_A2_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00B8)
#define		ECDSA_EQUATION_A2_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00BA)

#define		ECDSA_EQUATION_A3_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00BC)
#define		ECDSA_EQUATION_A3_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00BE)

#define		ECDSA_EQUATION_A4_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00C0)
#define		ECDSA_EQUATION_A4_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00C2)

#define		ECDSA_EQUATION_A5_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00C4)
#define		ECDSA_EQUATION_A5_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00C6)

#define		ECDSA_EQUATION_A6_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00C8)
#define		ECDSA_EQUATION_A6_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00CA)

#define		ECDSA_EQUATION_A7_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00CC)
#define		ECDSA_EQUATION_A7_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00CE)

#define		ECDSA_MONT_PNP0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00D0)
#define		ECDSA_MONT_PNP0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00D2)

#define		ECDSA_MONT_PNP1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00D4)
#define		ECDSA_MONT_PNP1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00D6)

#define		ECDSA_MONT_QNQ0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00D8)
#define		ECDSA_MONT_QNQ0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00DA)

#define		ECDSA_MONT_QNQ1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00DC)
#define		ECDSA_MONT_QNQ1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00DE)

#define		ECDSA_MONT_R20_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00E0)
#define		ECDSA_MONT_R20_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00E2)

#define		ECDSA_MONT_R21_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00E4)
#define		ECDSA_MONT_R21_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00E6)

#define		ECDSA_MONT_R22_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00E8)
#define		ECDSA_MONT_R22_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00EA)

#define		ECDSA_MONT_R23_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00EC)
#define		ECDSA_MONT_R23_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00EE)

#define		ECDSA_MONT_R24_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00F0)
#define		ECDSA_MONT_R24_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00F2)

#define		ECDSA_MONT_R25_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00F4)
#define		ECDSA_MONT_R25_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00F6)

#define		ECDSA_MONT_R26_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00F8)
#define		ECDSA_MONT_R26_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00FA)

#define		ECDSA_MONT_R27_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x00FC)
#define		ECDSA_MONT_R27_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x00FE)

#define		ECDSA_MONT_Q0_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0100)
#define		ECDSA_MONT_Q0_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0102)

#define		ECDSA_MONT_Q1_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0104)
#define		ECDSA_MONT_Q1_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0106)

#define		ECDSA_MONT_Q2_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0108)
#define		ECDSA_MONT_Q2_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x010A)

#define		ECDSA_MONT_Q3_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x010C)
#define		ECDSA_MONT_Q3_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x010E)

#define		ECDSA_MONT_Q4_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0110)
#define		ECDSA_MONT_Q4_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0112)

#define		ECDSA_MONT_Q5_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0114)
#define		ECDSA_MONT_Q5_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0116)

#define		ECDSA_MONT_Q6_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0118)
#define		ECDSA_MONT_Q6_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x011A)

#define		ECDSA_MONT_Q7_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x011C)
#define		ECDSA_MONT_Q7_L_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x011E)

#define		ECDSA_SIGVERIFY_KEYPAIR_R0_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0120)
#define		ECDSA_SIGVERIFY_KEYPAIR_R0_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0122)

#define		ECDSA_SIGVERIFY_KEYPAIR_R1_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0124)
#define		ECDSA_SIGVERIFY_KEYPAIR_R1_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0126)

#define		ECDSA_SIGVERIFY_KEYPAIR_R2_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0128)
#define		ECDSA_SIGVERIFY_KEYPAIR_R2_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x012A)

#define		ECDSA_SIGVERIFY_KEYPAIR_R3_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x012C)
#define		ECDSA_SIGVERIFY_KEYPAIR_R3_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x012E)

#define		ECDSA_SIGVERIFY_KEYPAIR_R4_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0130)
#define		ECDSA_SIGVERIFY_KEYPAIR_R4_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0132)

#define		ECDSA_SIGVERIFY_KEYPAIR_R5_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0134)
#define		ECDSA_SIGVERIFY_KEYPAIR_R5_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0136)

#define		ECDSA_SIGVERIFY_KEYPAIR_R6_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0138)
#define		ECDSA_SIGVERIFY_KEYPAIR_R6_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x013A)

#define		ECDSA_SIGVERIFY_KEYPAIR_R7_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x013C)
#define		ECDSA_SIGVERIFY_KEYPAIR_R7_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x013E)

#define		ECDSA_SIGVERIFY_KEYPAIR_S0_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0140)
#define		ECDSA_SIGVERIFY_KEYPAIR_S0_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0142)

#define		ECDSA_SIGVERIFY_KEYPAIR_S1_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0144)
#define		ECDSA_SIGVERIFY_KEYPAIR_S1_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0146)

#define		ECDSA_SIGVERIFY_KEYPAIR_S2_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0148)
#define		ECDSA_SIGVERIFY_KEYPAIR_S2_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x014A)

#define		ECDSA_SIGVERIFY_KEYPAIR_S3_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x014C)
#define		ECDSA_SIGVERIFY_KEYPAIR_S3_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x014E)

#define		ECDSA_SIGVERIFY_KEYPAIR_S4_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0150)
#define		ECDSA_SIGVERIFY_KEYPAIR_S4_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0152)

#define		ECDSA_SIGVERIFY_KEYPAIR_S5_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0154)
#define		ECDSA_SIGVERIFY_KEYPAIR_S5_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0156)

#define		ECDSA_SIGVERIFY_KEYPAIR_S6_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0158)
#define		ECDSA_SIGVERIFY_KEYPAIR_S6_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x015A)

#define		ECDSA_SIGVERIFY_KEYPAIR_S7_H_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x015C)
#define		ECDSA_SIGVERIFY_KEYPAIR_S7_L_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x015E)

#define		ECDSA_SHA_MESSAGE0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0160)
#define		ECDSA_SHA_MESSAGE0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0162)

#define		ECDSA_SHA_MESSAGE1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0164)
#define		ECDSA_SHA_MESSAGE1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0166)

#define		ECDSA_SHA_MESSAGE2_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0168)
#define		ECDSA_SHA_MESSAGE2_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x016A)

#define		ECDSA_SHA_MESSAGE3_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x016C)
#define		ECDSA_SHA_MESSAGE3_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x016E)

#define		ECDSA_SHA_MESSAGE4_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0170)
#define		ECDSA_SHA_MESSAGE4_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0172)

#define		ECDSA_SHA_MESSAGE5_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0174)
#define		ECDSA_SHA_MESSAGE5_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0176)

#define		ECDSA_SHA_MESSAGE6_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0178)
#define		ECDSA_SHA_MESSAGE6_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x017A)

#define		ECDSA_SHA_MESSAGE7_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x017C)
#define		ECDSA_SHA_MESSAGE7_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x017E)

#define		ECDSA_SHA_MESSAGE8_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0180)
#define		ECDSA_SHA_MESSAGE8_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0182)

#define		ECDSA_SHA_MESSAGE9_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0184)
#define		ECDSA_SHA_MESSAGE9_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0186)

#define		ECDSA_SHA_MESSAGE10_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0188)
#define		ECDSA_SHA_MESSAGE10_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x018A)

#define		ECDSA_SHA_MESSAGE11_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x018C)
#define		ECDSA_SHA_MESSAGE11_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x018E)

#define		ECDSA_SHA_MESSAGE12_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0190)
#define		ECDSA_SHA_MESSAGE12_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0192)

#define		ECDSA_SHA_MESSAGE13_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0194)
#define		ECDSA_SHA_MESSAGE13_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0196)

#define		ECDSA_SHA_MESSAGE14_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0198)
#define		ECDSA_SHA_MESSAGE14_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x019A)

#define		ECDSA_SHA_MESSAGE15_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x019C)
#define		ECDSA_SHA_MESSAGE15_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x019E)

#define		ECDSA_SHA_DATA_LEN0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01A0)
#define		ECDSA_SHA_DATA_LEN0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01A2)

#define		ECDSA_SHA_DATA_LEN1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01A4)
#define		ECDSA_SHA_DATA_LEN1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01A6)

#define		ECDSA_SHA_CONT_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x01A8)
#define		ECDSA_SHA_CONT_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x01AA)

#define		ECDSA_RANDOM_ON_OFF_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01AC)
#define		ECDSA_RANDOM_ON_OFF_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x01AE)

#define		ECDSA_SIGGEN_KEYPAIR_R0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0200)
#define		ECDSA_SIGGEN_KEYPAIR_R0_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0202)

#define		ECDSA_SIGGEN_KEYPAIR_R1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0204)
#define		ECDSA_SIGGEN_KEYPAIR_R1_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0206)

#define		ECDSA_SIGGEN_KEYPAIR_R2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0208)
#define		ECDSA_SIGGEN_KEYPAIR_R2_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x020A)

#define		ECDSA_SIGGEN_KEYPAIR_R3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x020C)
#define		ECDSA_SIGGEN_KEYPAIR_R3_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x020E)

#define		ECDSA_SIGGEN_KEYPAIR_R4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0210)
#define		ECDSA_SIGGEN_KEYPAIR_R4_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0212)

#define		ECDSA_SIGGEN_KEYPAIR_R5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0214)
#define		ECDSA_SIGGEN_KEYPAIR_R5_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0216)

#define		ECDSA_SIGGEN_KEYPAIR_R6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0218)
#define		ECDSA_SIGGEN_KEYPAIR_R6_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x021A)

#define		ECDSA_SIGGEN_KEYPAIR_R7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x021C)
#define		ECDSA_SIGGEN_KEYPAIR_R7_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x021E)

#define		ECDSA_SIGGEN_KEYPAIR_S0_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0220)
#define		ECDSA_SIGGEN_KEYPAIR_S0_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0222)

#define		ECDSA_SIGGEN_KEYPAIR_S1_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0224)
#define		ECDSA_SIGGEN_KEYPAIR_S1_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0226)

#define		ECDSA_SIGGEN_KEYPAIR_S2_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0228)
#define		ECDSA_SIGGEN_KEYPAIR_S2_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x022A)

#define		ECDSA_SIGGEN_KEYPAIR_S3_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x022C)
#define		ECDSA_SIGGEN_KEYPAIR_S3_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x022E)

#define		ECDSA_SIGGEN_KEYPAIR_S4_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0230)
#define		ECDSA_SIGGEN_KEYPAIR_S4_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0232)

#define		ECDSA_SIGGEN_KEYPAIR_S5_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0234)
#define		ECDSA_SIGGEN_KEYPAIR_S5_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0236)

#define		ECDSA_SIGGEN_KEYPAIR_S6_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0238)
#define		ECDSA_SIGGEN_KEYPAIR_S6_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x023A)

#define		ECDSA_SIGGEN_KEYPAIR_S7_H_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x023C)
#define		ECDSA_SIGGEN_KEYPAIR_S7_L_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x023E)

#define		ECDSA_SHA_OUT0_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0240)
#define		ECDSA_SHA_OUT0_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x0242)

#define		ECDSA_SHA_OUT1_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0244)
#define		ECDSA_SHA_OUT1_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x0246)

#define		ECDSA_SHA_OUT2_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0248)
#define		ECDSA_SHA_OUT2_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x024A)

#define		ECDSA_SHA_OUT3_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x024C)
#define		ECDSA_SHA_OUT3_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x024E)

#define		ECDSA_SHA_OUT4_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0250)
#define		ECDSA_SHA_OUT4_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x0252)

#define		ECDSA_SHA_OUT5_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0254)
#define		ECDSA_SHA_OUT5_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x0256)

#define		ECDSA_SHA_OUT6_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x0258)
#define		ECDSA_SHA_OUT6_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x025A)

#define		ECDSA_SHA_OUT7_H_REG_OFFSET							(ECDSA_ECC_BASE_ADDR+0x025C)
#define		ECDSA_SHA_OUT7_L_REG_OFFSET								(ECDSA_ECC_BASE_ADDR+0x025E)

#define		ECDSA_RANDOM_NUMBER0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0260)
#define		ECDSA_RANDOM_NUMBER0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0262)

#define		ECDSA_RANDOM_NUMBER1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0264)
#define		ECDSA_RANDOM_NUMBER1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0266)

#define		ECDSA_RANDOM_NUMBER2_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0268)
#define		ECDSA_RANDOM_NUMBER2_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x026A)

#define		ECDSA_RANDOM_NUMBER3_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x026C)
#define		ECDSA_RANDOM_NUMBER3_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x026E)

#define		ECDSA_RANDOM_NUMBER4_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0270)
#define		ECDSA_RANDOM_NUMBER4_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0272)

#define		ECDSA_RANDOM_NUMBER5_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0274)
#define		ECDSA_RANDOM_NUMBER5_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0276)

#define		ECDSA_RANDOM_NUMBER6_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0278)
#define		ECDSA_RANDOM_NUMBER6_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x027A)

#define		ECDSA_RANDOM_NUMBER7_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x027C)
#define		ECDSA_RANDOM_NUMBER7_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x027E)

/* ECIES */
/* 송신측 개인키 */
#define		ECIES_TRANS_RANDOM_NUMBER0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0280)
#define		ECIES_TRANS_RANDOM_NUMBER1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0284)
#define		ECIES_TRANS_RANDOM_NUMBER2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0288)
#define		ECIES_TRANS_RANDOM_NUMBER3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x028C)
#define		ECIES_TRANS_RANDOM_NUMBER4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0290)
#define		ECIES_TRANS_RANDOM_NUMBER5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0294)
#define		ECIES_TRANS_RANDOM_NUMBER6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0298)
#define		ECIES_TRANS_RANDOM_NUMBER7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x029C)

/* 수신측 개인키 */
#define		ECIES_RECEIVE_RANDOM_NUMBER0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02A0)
#define		ECIES_RECEIVE_RANDOM_NUMBER1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02A4)
#define		ECIES_RECEIVE_RANDOM_NUMBER2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02A8)
#define		ECIES_RECEIVE_RANDOM_NUMBER3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02AC)
#define		ECIES_RECEIVE_RANDOM_NUMBER4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02B0)
#define		ECIES_RECEIVE_RANDOM_NUMBER5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02B4)
#define		ECIES_RECEIVE_RANDOM_NUMBER6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02B8)
#define		ECIES_RECEIVE_RANDOM_NUMBER7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02BC)

/* 송신측 개인키 * 수신측 공개키 한것의 X좌표값  */
#define		ECIES_TRANS_PRIMITIVE_KEY_RX0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02C0)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02C4)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02C8)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02CC)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02D0)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02D4)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02D8)
#define		ECIES_TRANS_PRIMITIVE_KEY_RX7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02DC)

/* 송신측 개인키 * 수신측 공개키 한것의 Y좌표값  */
#define		ECIES_TRANS_PRIMITIVE_KEY_RY0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02E0)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02E4)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02E8)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02EC)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02F0)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02F4)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02F8)
#define		ECIES_TRANS_PRIMITIVE_KEY_RY7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x02FC)

/* 송신측 공개키 X좌표값  */
#define		ECIES_TRANS_PUBLIC_KEY_PX0_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0300)
#define		ECIES_TRANS_PUBLIC_KEY_PX1_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0304)
#define		ECIES_TRANS_PUBLIC_KEY_PX2_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0308)
#define		ECIES_TRANS_PUBLIC_KEY_PX3_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x030C)
#define		ECIES_TRANS_PUBLIC_KEY_PX4_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0310)
#define		ECIES_TRANS_PUBLIC_KEY_PX5_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0314)
#define		ECIES_TRANS_PUBLIC_KEY_PX6_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0318)
#define		ECIES_TRANS_PUBLIC_KEY_PX7_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x031C)

/* 송신측 공개키 Y좌표값  */
#define		ECIES_TRANS_PUBLIC_KEY_PY0_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0320)
#define		ECIES_TRANS_PUBLIC_KEY_PY1_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0324)
#define		ECIES_TRANS_PUBLIC_KEY_PY2_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0328)
#define		ECIES_TRANS_PUBLIC_KEY_PY3_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x032C)
#define		ECIES_TRANS_PUBLIC_KEY_PY4_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0330)
#define		ECIES_TRANS_PUBLIC_KEY_PY5_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0334)
#define		ECIES_TRANS_PUBLIC_KEY_PY6_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x0338)
#define		ECIES_TRANS_PUBLIC_KEY_PY7_REG_OFFSET					(ECDSA_ECC_BASE_ADDR+0x033C)

/* 수신측 개인키 * 송신측 공개키 한것의 X좌표값  */
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX0_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0340)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX1_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0344)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX2_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0348)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX3_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x034C)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX4_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0350)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX5_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0354)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX6_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0358)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RX7_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x035C)

/* 수신측 개인키 * 송신측 공개키 한것의 Y좌표값  */
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY0_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0360)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY1_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0364)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY2_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0368)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY3_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x036C)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY4_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0370)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY5_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0374)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY6_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0378)
#define		ECIES_RECEIVER_PRIMITIVE_KEY_RY7_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x037C)

/* 수신측 공개키 X좌표값  */
#define		ECIES_RECEIVER_PUBLIC_KEY_PX0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0380)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0384)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0388)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x038C)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0390)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0394)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x0398)
#define		ECIES_RECEIVER_PUBLIC_KEY_PX7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x039C)

/* 수신측 공개키 Y좌표값  */
#define		ECIES_RECEIVER_PUBLIC_KEY_PY0_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03A0)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY1_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03A4)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY2_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03A8)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY3_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03AC)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY4_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03B0)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY5_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03B4)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY6_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03B8)
#define		ECIES_RECEIVER_PUBLIC_KEY_PY7_REG_OFFSET				(ECDSA_ECC_BASE_ADDR+0x03BC)

/* 송신측 공개키 X좌표값  */
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R0_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03C0)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R1_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03C4)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R2_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03C8)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R3_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03CC)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R4_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03D0)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R5_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03D4)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R6_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03D8)
#define		ECIES_TRANS_PUBLIC_PX_TO_REC_R7_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03DC)

/* 송신측 공개키 Y좌표값  */
#if 0	/* 사용안함 */
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S0_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03E0)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S1_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03E4)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S2_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03E8)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S3_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03EC)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S4_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03F0)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S5_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03F4)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S6_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03F8)
#define		ECIES_TRANS_PUBLIC_PY_TO_REC_S7_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x03FC)
#else
#define		ECIES_TRANS_PUBLIC_PY_0_BIT_TO_RECEIVE_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x03E0)
#endif


/* 수신측 공개키 X좌표값  */
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R0_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0400)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R1_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0404)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R2_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0408)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R3_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x040C)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R4_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0410)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R5_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0414)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R6_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0418)
#define		ECIES_RECEIVER_PUBLIC_PX_TO_TRANS_R7_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x041C)

/* 수신측 공개키 Y좌표값  */
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S0_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0420)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S1_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0424)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S2_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0428)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S3_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x042C)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S4_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0430)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S5_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0434)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S6_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x0438)
#define		ECIES_RECEIVER_PUBLIC_PY_TO_TRANS_S7_REG_OFFSET		(ECDSA_ECC_BASE_ADDR+0x043C)

#define		AES_KEY0_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0440)
#define		AES_KEY0_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0442)

#define		AES_KEY1_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0444)
#define		AES_KEY1_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0446)

#define		AES_KEY2_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0448)
#define		AES_KEY2_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x044A)

#define		AES_KEY3_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x044C)
#define		AES_KEY3_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x044E)

#define		AES_DATA0_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0450)
#define		AES_DATA0_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0452)

#define		AES_DATA1_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0454)
#define		AES_DATA1_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0456)

#define		AES_DATA2_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0458)
#define		AES_DATA2_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x045A)

#define		AES_DATA3_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x045C)
#define		AES_DATA3_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x045E)

#define		AES_OUT0_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0460)
#define		AES_OUT0_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0462)

#define		AES_OUT1_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0464)
#define		AES_OUT1_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0466)

#define		AES_OUT2_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x0468)
#define		AES_OUT2_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x046A)

#define		AES_OUT3_H_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x046C)
#define		AES_OUT3_L_REG_OFFSET									(ECDSA_ECC_BASE_ADDR+0x046E)

#define		ECDSA_EQUATION_B0_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0470)
#define		ECDSA_EQUATION_B0_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0472)

#define		ECDSA_EQUATION_B1_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0474)
#define		ECDSA_EQUATION_B1_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0476)

#define		ECDSA_EQUATION_B2_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0478)
#define		ECDSA_EQUATION_B2_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x047A)

#define		ECDSA_EQUATION_B3_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x047C)
#define		ECDSA_EQUATION_B3_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x047E)

#define		ECDSA_EQUATION_B4_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0480)
#define		ECDSA_EQUATION_B4_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0482)

#define		ECDSA_EQUATION_B5_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0484)
#define		ECDSA_EQUATION_B5_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0486)

#define		ECDSA_EQUATION_B6_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x0488)
#define		ECDSA_EQUATION_B6_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x048A)

#define		ECDSA_EQUATION_B7_H_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x048C)
#define		ECDSA_EQUATION_B7_L_REG_OFFSET						(ECDSA_ECC_BASE_ADDR+0x048E)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y0_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0500)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y0_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0502)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y1_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0504)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y1_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0506)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y2_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0508)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y2_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x050A)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y3_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x050C)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y3_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x050E)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y4_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0510)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y4_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0512)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y5_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0514)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y5_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0516)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y6_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0518)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y6_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x051A)

#define		ECIES_TRANS_RECEIVE_RECOVERY_Y7_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x051C)
#define		ECIES_TRANS_RECEIVE_RECOVERY_Y7_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x051E)


/* ECDSA 송신측 공개키 X좌표값  */
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R0_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0600)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R1_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0604)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R2_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0608)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R3_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x060C)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R4_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0610)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R5_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0614)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R6_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0618)
#define		ECDSA_TRANS_PUBLIC_PX_TO_REC_R7_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x061C)

/* ECDSA 송신측 공개키 Y좌표의 0번째 비트   */
#define		ECDSA_TRANS_PUBLIC_PY_0_BIT_TO_RECEIVE_REG_OFFSET	(ECDSA_ECC_BASE_ADDR+0x0620)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y0_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0630)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y0_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0632)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y1_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0634)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y1_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0636)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y2_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0638)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y2_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x063A)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y3_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x063C)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y3_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x063E)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y4_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0640)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y4_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0642)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y5_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0644)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y5_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0646)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y6_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x0648)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y6_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x064A)

#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y7_H_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x064C)
#define		ECDSA_TRANS_RECEIVE_RECOVERY_Y7_L_REG_OFFSET			(ECDSA_ECC_BASE_ADDR+0x064E)


/* ECC ENABLE Register Bit */
#define		ECIES_KEY_RECOVERY_ENABLE_BIT							0x00000100
#define		ECDSA_KEY_RECOVERY_ENABLE_BIT							0x00000080
#define		AES_ENABLE_BIT											0x00000040
#define		RECEIVER_PUBLIC_ENABLE_BIT								0x00000020
#define		RECEIVER_PRIMITIVE_ENABLE_BIT							0x00000010
#define		TRANSFER_PUBLIC_ENABLE_BIT								0x00000008
#define		TRANSFER_PRIMITIVE_ENABLE_BIT							0x00000004
#define		SIGNATURE_VERIFY_ENABLE_BIT								0x00000002
#define		SIGNATURE_GEN_ENABLE_BIT									0x00000001

/* ECC STATUS Register Bit */
#if 0
#define		ALL_STATUS_CLEAR_BIT										0x10000000
#define		IKEY_RECOVERY_DONE_BIT										0x08000000
#define		AES_DONE_BIT												0x04000000
#define		TRANS_PRIMITIVE_DONE_BIT									0x02000000
#define		TRANS_PUBLIC_GEN_DONE_BIT									0x01000000
#define		REC_PRIMITIVE_DONE_BIT										0x00800000
#define		REC_PUBLIC_GEN_DONE_BIT									0x00400000
#define		TRANS_REC_VALID_BIT										0x00200000
#define		SHA_BUSY_STATUS_BIT										0x00100000
#define		SHA_DONE_STATUS_BIT										0x00080000
#define		SIGGEN_DONE_STATUS_BIT										0x00040000
#define		SIGVERIFY_DONE_STATUS_BIT									0x00020000
#define		SIGVERIFY_VALID_STATUS_BIT									0x00010000
#else
#define		ALL_STATUS_CLEAR_BIT										0x00002000
#define		ECIES_RECOVERY_DONE_BIT									0x00001000
#define		ECDSA_RECOVERY_DONE_BIT									0x00000800
#define		AES_DONE_BIT												0x00000400
#define		TRANS_PRIMITIVE_DONE_BIT									0x00000200
#define		TRANS_PUBLIC_GEN_DONE_BIT								0x00000100
#define		REC_PRIMITIVE_DONE_BIT									0x00000080
#define		REC_PUBLIC_GEN_DONE_BIT									0x00000040
#define		TRANS_REC_VALID_BIT										0x00000020
#define		SHA_BUSY_STATUS_BIT										0x00000010
#define		SHA_DONE_STATUS_BIT										0x00000008
#define		SIGGEN_DONE_STATUS_BIT									0x00000004
#define		SIGVERIFY_DONE_STATUS_BIT								0x00000002
#define		SIGVERIFY_VALID_STATUS_BIT								0x00000001
#endif


/* RANDOM SELECT Register Bit */
#define		RECEIVER_PRIVATE_RANDOM_SEL_BIT							0x00040000
#define		TRANSFER_PRIVATE_RANDOM_SEL_BIT						0x00020000
#define		SIGNATURE_GEN_RANDOM_SEL_BIT							0x00010000


/* SHA Control Register Bit */
#define		SHA_CONTROL_ISHA_START_BIT								0x00000004
#define		SHA_CONTROL_ISHA_FIRST_BIT								0x00000002
#define		SHA_CONTROL_ISHA_SELECT_BIT								0x00000001

/* SHA Generate Verify Initial Bit */
#define		IKEY_RECOVERY_INITIAL_BIT									0x00000020
#define		ECIES_INITIAL_BIT											0x00000008
#define		SIGNATURE_VERIFICATION_INITIAL_BIT						0x00000004
#define		SIGNATURE_GEN_INITIAL_BIT								0x00000002
#define		SHA_INITIAL_BIT											0x00000001

/* RANDOM Number On/OFF Selection */
#define		ECDSA224_RANDOM_ENABLE									0x00010000
#define		ECDSA224_RANDOM_DISABLE									0x00020000
#define		ECDSA256_RANDOM_ENABLE									0x00050000
#define		ECDSA256_RANDOM_DISABLE									0x00060000


/* WAVE ECC Command */
#define		ECDSA_SIGNATURE_GENERATION								1
#define		ECDSA_SIGNATURE_VERIFY									2

/* WAVE ECC Interrupt Stauts */
#define		SHA_DONE													1
#define		AES_DONE													2
#define		ECDSA_SIGNATURE_GEN_DONE								3
#define		ECDSA_SIGNATURE_VERIFY_DONE								4
#define		ECIES_TRANS_PRIMITIVE_DONE								5
#define		ECIES_RECEIVE_PRIMITIVE_DONE								6



/* PKAlgorithm */
#define		ECDSA_NISTP224_WITH_SHA224								0
#define		ECDSA_NISTP256_WITH_SHA256								1
#define		ECIES_NISTP256												2

