

#if 0	//SHKO, Origin
#define		WAVE_MAC_A_BASE_ADDR									(0x00000)
#define		WAVE_MODEM_A_BASE_ADDR									(0x10000)
#define		WAVE_TOP_A_BASE_ADDR									(0x20000)

#define		WAVE_MAC_B_BASE_ADDR									(0x30000)
#define		WAVE_MODEM_B_BASE_ADDR									(0x40000)
#define		WAVE_TOP_B_BASE_ADDR									(0x50000)
#else
#define		WAVE_TOP_BASE_ADDR										(0x00000)
#define		WAVE_MAC_A_BASE_ADDR									(0x10000)
#define		WAVE_MODEM_A_BASE_ADDR									(0x20000)


#define		WAVE_MAC_B_BASE_ADDR									(0x30000)
#define		WAVE_MODEM_B_BASE_ADDR									(0x40000)
#define		WAVE_ECDSA_BASE_ADDR									(0x50000)
#endif




/* SHKO : WAVE MAC 레지스터는 ETRI MAC 레지스터 설명과 똑같고, 단지 다른 점은 ETRI MAC 레지스터 하나가 */
/* HIGH, LOW 두개의 레지스터로 나뉘어 진다. */
/* WAVE MODEM 레지스터와 TOP 레지스터는 강현수씨가 보내준, Modem_reg_list.xslx 파일 그대로를 참조하면 된다. */
#define		WAVE_MAC_A_INT_STATUS_H_REG_OFFSET					(WAVE_TOP_BASE_ADDR + 0x00000)		/* 0 */
#define		WAVE_MAC_A_INT_STATUS_L_REG_OFFSET					(WAVE_TOP_BASE_ADDR + 0x00002)		/* 0 */

#define		WAVE_MAC_B_INT_STATUS_H_REG_OFFSET					(WAVE_TOP_BASE_ADDR + 0x00010)		/* 0 */
#define		WAVE_MAC_B_INT_STATUS_L_REG_OFFSET					(WAVE_TOP_BASE_ADDR + 0x00012)		/* 0 */

#define		WAVE_MAC_A_INT_MASK_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00004)		/* 0xFFFFFF */
#define		WAVE_MAC_A_INT_MASK_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00006)		/* 0xFFFFFF */

#define		WAVE_MAC_B_INT_MASK_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00014)		/* 0xFFFFFF */
#define		WAVE_MAC_B_INT_MASK_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00016)		/* 0xFFFFFF */

#define		WAVE_MAC_A_INT_COUNT_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00008)
#define		WAVE_MAC_A_INT_COUNT_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x0000A)

#define		WAVE_MAC_B_INT_COUNT_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00018)
#define		WAVE_MAC_B_INT_COUNT_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x0001A)	

#define		WAVE_ECDSA_INT_MASK_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00024)		/* 0xFFFFFF */
#define		WAVE_ECDSA_INT_MASK_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x00026)		/* 0xFFFFFF */

#define		WAVE_CONTROL_H_REG_OFFSET								(WAVE_TOP_BASE_ADDR + 0x00030)		/* 0xFFFFFF */
#define		WAVE_CONTROL_L_REG_OFFSET								(WAVE_TOP_BASE_ADDR + 0x00032)		/* 0xFFFFFF */

#define		WAVE_MODE_SET_H_REG_OFFSET								(WAVE_TOP_BASE_ADDR + 0x00034)		/* 0xFFFFFF */
#define		WAVE_MODE_SET_L_REG_OFFSET								(WAVE_TOP_BASE_ADDR + 0x00036)		/* 0xFFFFFF */

#define		WAVE_MULTICH_SET_H_REG_OFFSET							(WAVE_TOP_BASE_ADDR + 0x00038)		/* 0xFFFFFF */
#define		WAVE_MULTICH_SET_L_REG_OFFSET							(WAVE_TOP_BASE_ADDR + 0x0003A)		/* 0xFFFFFF */

#define		WAVE_MAC_HW_VERSION_H_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x0003C)	
#define		WAVE_MAC_HW_VERSION_L_REG_OFFSET						(WAVE_TOP_BASE_ADDR + 0x0003E)


/* MAC */
#define		WAVE_MAC_A_CCH_AC1_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01000)		/* 0 */
#define		WAVE_MAC_A_CCH_AC1_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01002)		/* 0 */

#define		WAVE_MAC_B_CCH_AC1_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01000)		/* 0 */
#define		WAVE_MAC_B_CCH_AC1_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01002)		/* 0 */

#define		WAVE_MAC_A_CCH_AC1_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01004)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC1_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01006)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC1_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01004)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC1_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01006)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC1_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01008)		/* 0x1000 */
#define		WAVE_MAC_A_CCH_AC1_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0100A)		/* 0x1000 */

#define		WAVE_MAC_B_CCH_AC1_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01008)		/* 0x1000 */
#define		WAVE_MAC_B_CCH_AC1_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0100A)		/* 0x1000 */

#define		WAVE_MAC_A_CCH_AC2_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01010)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC2_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01012)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC2_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01010)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC2_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01012)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC2_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01014)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC2_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01016)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC2_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01014)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC2_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01016)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC2_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01018)		/* 0x1000 */
#define		WAVE_MAC_A_CCH_AC2_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0101A)		/* 0x1000 */

#define		WAVE_MAC_B_CCH_AC2_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01018)		/* 0x1000 */
#define		WAVE_MAC_B_CCH_AC2_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0101A)		/* 0x1000 */

#define		WAVE_MAC_A_CCH_AC3_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01020)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC3_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01022)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC3_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01020)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC3_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01022)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC3_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01024)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC3_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01026)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC3_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01024)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC3_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01026)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC3_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01028)		/* 0x1000 */
#define		WAVE_MAC_A_CCH_AC3_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0102A)		/* 0x1000 */

#define		WAVE_MAC_B_CCH_AC3_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01028)		/* 0x1000 */
#define		WAVE_MAC_B_CCH_AC3_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0102A)		/* 0x1000 */

#define		WAVE_MAC_A_CCH_AC4_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01030)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC4_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01032)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC4_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01030)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC4_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01032)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC4_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01034)		/* 0x0 */
#define		WAVE_MAC_A_CCH_AC4_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01036)		/* 0x0 */

#define		WAVE_MAC_B_CCH_AC4_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01034)		/* 0x0 */
#define		WAVE_MAC_B_CCH_AC4_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01036)		/* 0x0 */

#define		WAVE_MAC_A_CCH_AC4_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01038)		/* 0x1000 */
#define		WAVE_MAC_A_CCH_AC4_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0103A)		/* 0x1000 */

#define		WAVE_MAC_B_CCH_AC4_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01038)		/* 0x1000 */
#define		WAVE_MAC_B_CCH_AC4_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0103A)		/* 0x1000 */

#define		WAVE_MAC_A_SCH_AC1_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01040)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC1_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01042)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC1_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01040)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC1_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01042)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC1_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01044)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC1_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01046)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC1_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01044)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC1_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01046)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC1_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01048)		/* 0x1000 */
#define		WAVE_MAC_A_SCH_AC1_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0104A)		/* 0x1000 */

#define		WAVE_MAC_B_SCH_AC1_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01048)		/* 0x1000 */
#define		WAVE_MAC_B_SCH_AC1_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0104A)		/* 0x1000 */

#define		WAVE_MAC_A_SCH_AC2_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01050)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC2_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01052)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC2_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01050)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC2_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01052)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC2_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01054)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC2_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01056)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC2_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01054)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC2_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01056)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC2_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01058)		/* 0x1000 */
#define		WAVE_MAC_A_SCH_AC2_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0105A)		/* 0x1000 */

#define		WAVE_MAC_B_SCH_AC2_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01058)		/* 0x1000 */
#define		WAVE_MAC_B_SCH_AC2_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0105A)		/* 0x1000 */

#define		WAVE_MAC_A_SCH_AC3_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01060)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC3_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01062)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC3_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01060)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC3_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01062)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC3_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01064)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC3_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01066)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC3_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01064)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC3_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01066)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC3_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01068)		/* 0x1000 */
#define		WAVE_MAC_A_SCH_AC3_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0106A)		/* 0x1000 */

#define		WAVE_MAC_B_SCH_AC3_FREE_SPACE_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01068)		/* 0x1000 */
#define		WAVE_MAC_B_SCH_AC3_FREE_SPACE_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0106A)		/* 0x1000 */

#define		WAVE_MAC_A_SCH_AC4_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01070)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC4_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01072)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC4_FRAME_CONTENTS_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01070)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC4_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01072)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC4_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01074)		/* 0x0 */
#define		WAVE_MAC_A_SCH_AC4_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x01076)		/* 0x0 */

#define		WAVE_MAC_B_SCH_AC4_FRAME_INFO_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01074)		/* 0x0 */
#define		WAVE_MAC_B_SCH_AC4_FRAME_INFO_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x01076)		/* 0x0 */

#define		WAVE_MAC_A_SCH_AC4_FREE_SPACE_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x01078)		/* 0x1000 */
#define		WAVE_MAC_A_SCH_AC4_FREE_SPACE_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0107A)		/* 0x1000 */

#define		WAVE_MAC_B_SCH_AC4_FREE_SPACE_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x01078)		/* 0x1000 */
#define		WAVE_MAC_B_SCH_AC4_FREE_SPACE_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0107A)		/* 0x1000 */


#define		WAVE_MAC_A_EXTRA_QUEUE_FRAME_CONTENTS_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01080)		/* 0x0 */
#define		WAVE_MAC_A_EXTRA_QUEUE_FRAME_CONTENTS_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01082)		/* 0x0 */

#define		WAVE_MAC_B_EXTRA_QUEUE_FRAME_CONTENTS_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01080)		/* 0x0 */
#define		WAVE_MAC_B_EXTRA_QUEUE_FRAME_CONTENTS_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01082)		/* 0x0 */

#define		WAVE_MAC_A_EXTRA_QUEUE_FRAME_INFO_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01084)		/* 0x0 */
#define		WAVE_MAC_A_EXTRA_QUEUE_FRAME_INFO_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01086)		/* 0x0 */

#define		WAVE_MAC_B_EXTRA_QUEUE_FRAME_INFO_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01084)		/* 0x0 */
#define		WAVE_MAC_B_EXTRA_QUEUE_FRAME_INFO_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01086)		/* 0x0 */


#define		WAVE_MAC_A_RX_DATA_QUEUE_DATA_FRAME_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01100)		/* 0x0 */
#define		WAVE_MAC_A_RX_DATA_QUEUE_DATA_FRAME_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01102)		/* 0x0 */

#define		WAVE_MAC_B_RX_DATA_QUEUE_DATA_FRAME_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01100)		/* 0x0 */
#define		WAVE_MAC_B_RX_DATA_QUEUE_DATA_FRAME_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01102)		/* 0x0 */

#define		WAVE_MAC_A_RX_INFO_QUEUE_FOR_DATA_FRAME_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01104)		/* 0x0 */
#define		WAVE_MAC_A_RX_INFO_QUEUE_FOR_DATA_FRAME_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x01106)		/* 0x0 */

#define		WAVE_MAC_B_RX_INFO_QUEUE_FOR_DATA_FRAME_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01104)		/* 0x0 */
#define		WAVE_MAC_B_RX_INFO_QUEUE_FOR_DATA_FRAME_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x01106)		/* 0x0 */

#define		WAVE_MAC_A_RX_DATA_OVERFLOW_DISCARD_COUNT_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01108)
#define		WAVE_MAC_A_RX_DATA_OVERFLOW_DISCARD_COUNT_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x0110A)

#define		WAVE_MAC_B_RX_DATA_OVERFLOW_DISCARD_COUNT_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01108)
#define		WAVE_MAC_B_RX_DATA_OVERFLOW_DISCARD_COUNT_L_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x0110A)

#define		WAVE_MAC_A_RX_DATA_QUEUE_FOR_MANAGE_FRAME_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01110)		/* 0x0 */
#define		WAVE_MAC_A_RX_DATA_QUEUE_FOR_MANAGE_FRAME_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01112)		/* 0x0 */

#define		WAVE_MAC_B_RX_DATA_QUEUE_FOR_MANAGE_FRAME_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01110)		/* 0x0 */
#define		WAVE_MAC_B_RX_DATA_QUEUE_FOR_MANAGE_FRAME_L_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01112)		/* 0x0 */

#define		WAVE_MAC_A_RX_INFO_QUEUE_FOR_MANAGE_FRAME_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01114)		/* 0x0 */
#define		WAVE_MAC_A_RX_INFO_QUEUE_FOR_MANAGE_FRAME_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01116)		/* 0x0 */

#define		WAVE_MAC_B_RX_INFO_QUEUE_FOR_MANAGE_FRAME_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01114)		/* 0x0 */
#define		WAVE_MAC_B_RX_INFO_QUEUE_FOR_MANAGE_FRAME_L_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01116)		/* 0x0 */

#define		WAVE_MAC_A_RX_MANAGE_OVERFLOW_DISCARD_COUNT_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x01118)
#define		WAVE_MAC_A_RX_MANAGE_OVERFLOW_DISCARD_COUNT_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x0111A)

#define		WAVE_MAC_B_RX_MANAGE_OVERFLOW_DISCARD_COUNT_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x01118)
#define		WAVE_MAC_B_RX_MANAGE_OVERFLOW_DISCARD_COUNT_L_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x0111A)

#define		WAVE_MAC_A_TX_FRAME_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02000)		/* 0x0 */
#define		WAVE_MAC_A_TX_FRAME_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02002)		/* 0x0 */

#define		WAVE_MAC_B_TX_FRAME_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02000)		/* 0x0 */
#define		WAVE_MAC_B_TX_FRAME_COUNTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02002)		/* 0x0 */

#define		WAVE_MAC_A_RX_FRAME_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02004)		/* 0x0 */
#define		WAVE_MAC_A_RX_FRAME_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02006)		/* 0x0 */

#define		WAVE_MAC_B_RX_FRAME_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02004)		/* 0x0 */
#define		WAVE_MAC_B_RX_FRAME_COUNTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02006)		/* 0x0 */

#define		WAVE_MAC_A_CRC_ERR_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02008)		/* 0x0 */
#define		WAVE_MAC_A_CRC_ERR_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0200A)		/* 0x0 */

#define		WAVE_MAC_B_CRC_ERR_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02008)		/* 0x0 */
#define		WAVE_MAC_B_CRC_ERR_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0200A)		/* 0x0 */

#define		WAVE_MAC_A_PHY_ERR_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0200C)		/* 0x0 */
#define		WAVE_MAC_A_PHY_ERR_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0200E)		/* 0x0 */

#define		WAVE_MAC_B_PHY_ERR_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0200C)		/* 0x0 */
#define		WAVE_MAC_B_PHY_ERR_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0200E)		/* 0x0 */

#define		WAVE_MAC_A_TX_DATA_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02010)		/* 0x0 */
#define		WAVE_MAC_A_TX_DATA_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02012)		/* 0x0 */

#define		WAVE_MAC_B_TX_DATA_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02010)		/* 0x0 */
#define		WAVE_MAC_B_TX_DATA_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02012)		/* 0x0 */

#define		WAVE_MAC_A_TX_RTS_COUNTER_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02014)		/* 0x0 */
#define		WAVE_MAC_A_TX_RTS_COUNTER_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02016)		/* 0x0 */

#define		WAVE_MAC_B_TX_RTS_COUNTER_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02014)		/* 0x0 */
#define		WAVE_MAC_B_TX_RTS_COUNTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02016)		/* 0x0 */

#define		WAVE_MAC_A_TX_CTS_COUNTER_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02018)		/* 0x0 */
#define		WAVE_MAC_A_TX_CTS_COUNTER_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0201A)		/* 0x0 */

#define		WAVE_MAC_B_TX_CTS_COUNTER_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02018)		/* 0x0 */
#define		WAVE_MAC_B_TX_CTS_COUNTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0201A)		/* 0x0 */

#define		WAVE_MAC_A_TX_ACK_COUNTER_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0201C)		/* 0x0 */
#define		WAVE_MAC_A_TX_ACK_COUNTER_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0201E)		/* 0x0 */

#define		WAVE_MAC_B_TX_ACK_COUNTER_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0201C)		/* 0x0 */
#define		WAVE_MAC_B_TX_ACK_COUNTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0201E)		/* 0x0 */

#define		WAVE_MAC_A_RX_DATA_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02020)		/* 0x0 */
#define		WAVE_MAC_A_RX_DATA_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02022)		/* 0x0 */

#define		WAVE_MAC_B_RX_DATA_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02020)		/* 0x0 */
#define		WAVE_MAC_B_RX_DATA_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02022)		/* 0x0 */

#define		WAVE_MAC_A_RX_MY_RTS_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02024)		/* 0x0 */
#define		WAVE_MAC_A_RX_MY_RTS_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02026)		/* 0x0 */

#define		WAVE_MAC_B_RX_MY_RTS_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02024)		/* 0x0 */
#define		WAVE_MAC_B_RX_MY_RTS_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02026)		/* 0x0 */

#define		WAVE_MAC_A_RX_MY_CTS_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02028)		/* 0x0 */
#define		WAVE_MAC_A_RX_MY_CTS_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0202A)		/* 0x0 */

#define		WAVE_MAC_B_RX_MY_CTS_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02028)		/* 0x0 */
#define		WAVE_MAC_B_RX_MY_CTS_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0202A)		/* 0x0 */

#define		WAVE_MAC_A_RX_MY_ACK_COUNTER_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0202C)		/* 0x0 */
#define		WAVE_MAC_A_RX_MY_ACK_COUNTER_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x0202E)		/* 0x0 */

#define		WAVE_MAC_B_RX_MY_ACK_COUNTER_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0202C)		/* 0x0 */
#define		WAVE_MAC_B_RX_MY_ACK_COUNTER_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x0202E)		/* 0x0 */

#define		WAVE_MAC_A_TX_DISCARD_FRAME_COUNTER_H_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x02030)		/* 0x0 */
#define		WAVE_MAC_A_TX_DISCARD_FRAME_COUNTER_L_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x02032)		/* 0x0 */

#define		WAVE_MAC_B_TX_DISCARD_FRAME_COUNTER_H_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x02030)		/* 0x0 */
#define		WAVE_MAC_B_TX_DISCARD_FRAME_COUNTER_L_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x02032)		/* 0x0 */

#define		WAVE_MAC_A_RX_OTHER_RTS_COUNTER_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02034)		/* 0 */
#define		WAVE_MAC_A_RX_OTHER_RTS_COUNTER_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02036)		/* 0 */

#define		WAVE_MAC_B_RX_OTHER_RTS_COUNTER_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02034)		/* 0 */
#define		WAVE_MAC_B_RX_OTHER_RTS_COUNTER_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02036)		/* 0 */

#define		WAVE_MAC_A_RX_OTHER_CTS_COUNTER_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02038)		/* 0 */
#define		WAVE_MAC_A_RX_OTHER_CTS_COUNTER_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0203A)		/* 0 */

#define		WAVE_MAC_B_RX_OTHER_CTS_COUNTER_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02038)		/* 0 */
#define		WAVE_MAC_B_RX_OTHER_CTS_COUNTER_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0203A)		/* 0 */

#define		WAVE_MAC_A_RX_OTHER_ACK_COUNTER_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0203C)		/* 0 */
#define		WAVE_MAC_A_RX_OTHER_ACK_COUNTER_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0203E)		/* 0 */

#define		WAVE_MAC_B_RX_OTHER_ACK_COUNTER_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0203C)		/* 0 */
#define		WAVE_MAC_B_RX_OTHER_ACK_COUNTER_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0203E)		/* 0 */

#define		WAVE_MAC_A_TIMING_CHARACTER_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02040)		/* 0 */
#define		WAVE_MAC_A_TIMING_CHARACTER_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02042)		/* 0 */

#define		WAVE_MAC_B_TIMING_CHARACTER_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02040)		/* 0 */
#define		WAVE_MAC_B_TIMING_CHARACTER_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02042)		/* 0 */

#define		WAVE_MAC_A_DEST_ADDR16_REG_OFFSET							(WAVE_MAC_A_BASE_ADDR + 0x02046)		/* 0, change */

#define		WAVE_MAC_B_DEST_ADDR16_REG_OFFSET							(WAVE_MAC_B_BASE_ADDR + 0x02046)		/* 0, change */

#define		WAVE_MAC_A_DEST_ADDR32_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02048)		/* 0x03, change */
#define		WAVE_MAC_A_DEST_ADDR32_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0204A)		/* 0x03, change */

#define		WAVE_MAC_B_DEST_ADDR32_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02048)		/* 0x03, change */
#define		WAVE_MAC_B_DEST_ADDR32_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0204A)		/* 0x03, change */

#define		WAVE_MAC_A_RTS_DEST_ADDR16_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0204E)		/* 0, change */

#define		WAVE_MAC_B_RTS_DEST_ADDR16_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0204E)		/* 0, change */

#define		WAVE_MAC_A_RTS_DEST_ADDR32_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02050)		/* 0x03, change */
#define		WAVE_MAC_A_RTS_DEST_ADDR32_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02052)		/* 0x03, change */

#define		WAVE_MAC_B_RTS_DEST_ADDR32_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02050)		/* 0x03, change */
#define		WAVE_MAC_B_RTS_DEST_ADDR32_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02052)		/* 0x03, change */

#define		WAVE_MAC_A_RTS_SRC_ADDR16_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02056)		/* 0, change */

#define		WAVE_MAC_B_RTS_SRC_ADDR16_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02056)		/* 0, change */

#define		WAVE_MAC_A_RTS_SRC_ADDR32_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02058)		/* 0x03, change */
#define		WAVE_MAC_A_RTS_SRC_ADDR32_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0205A)		/* 0x03, change */

#define		WAVE_MAC_B_RTS_SRC_ADDR32_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02058)		/* 0x03, change */
#define		WAVE_MAC_B_RTS_SRC_ADDR32_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0205A)

#define		WAVE_MAC_A_ADDR16_REG_OFFSET								(WAVE_MAC_A_BASE_ADDR + 0x02082)		/* 0, change */

#define		WAVE_MAC_B_ADDR16_REG_OFFSET								(WAVE_MAC_B_BASE_ADDR + 0x02082)		/* 0, change */

#define		WAVE_MAC_A_ADDR32_H_REG_OFFSET							(WAVE_MAC_A_BASE_ADDR + 0x02084)		/* 0x03, change */
#define		WAVE_MAC_A_ADDR32_L_REG_OFFSET							(WAVE_MAC_A_BASE_ADDR + 0x02086)		/* 0x03, change */

#define		WAVE_MAC_B_ADDR32_H_REG_OFFSET							(WAVE_MAC_B_BASE_ADDR + 0x02084)		/* 0x03, change */
#define		WAVE_MAC_B_ADDR32_L_REG_OFFSET							(WAVE_MAC_B_BASE_ADDR + 0x02086)		/* 0x03, change */

#define		WAVE_MAC_A_MULTICAST0_16_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0208A)		/* 0xFFFF */

#define		WAVE_MAC_B_MULTICAST0_16_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0208A)		/* 0xFFFF */

#define		WAVE_MAC_A_MULTICAST0_32_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0208C)		/* 0xFFFFFFFF */
#define		WAVE_MAC_A_MULTICAST0_32_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0208E)		/* 0xFFFFFFFF */

#define		WAVE_MAC_B_MULTICAST0_32_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0208C)		/* 0xFFFFFFFF */
#define		WAVE_MAC_B_MULTICAST0_32_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0208E)		/* 0xFFFFFFFF */

#define		WAVE_MAC_A_MULTICAST1_16_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02092)		/* 0xFFFF */

#define		WAVE_MAC_B_MULTICAST1_16_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02092)		/* 0xFFFF */

#define		WAVE_MAC_A_MULTICAST1_32_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02094)		/* 0xFFFFFFFF */
#define		WAVE_MAC_A_MULTICAST1_32_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02096)		/* 0xFFFFFFFF */

#define		WAVE_MAC_B_MULTICAST1_32_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02094)		/* 0xFFFFFFFF */
#define		WAVE_MAC_B_MULTICAST1_32_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02096)		/* 0xFFFFFFFF */

#define		WAVE_MAC_A_MULTICAST2_16_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0209A)		/* 0xFFFF */

#define		WAVE_MAC_B_MULTICAST2_16_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0209A)		/* 0xFFFF */

#define		WAVE_MAC_A_MULTICAST2_32_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0209C)		/* 0xFFFFFFFF */
#define		WAVE_MAC_A_MULTICAST2_32_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0209E)		/* 0xFFFFFFFF */

#define		WAVE_MAC_B_MULTICAST2_32_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0209C)		/* 0xFFFFFFFF */
#define		WAVE_MAC_B_MULTICAST2_32_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0209E)		/* 0xFFFFFFFF */

#define		WAVE_MAC_A_SHORT_RETRY_LIMIT_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x020A2)		/* 0x07 */

#define		WAVE_MAC_B_SHORT_RETRY_LIMIT_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x020A2)		/* 0x07 */

#define		WAVE_MAC_A_LONG_RETRY_LIMIT_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x020A6)		/* 0x04 */

#define		WAVE_MAC_B_LONG_RETRY_LIMIT_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x020A6)		/* 0x04 */

#define		WAVE_MAC_A_MODE_REG_OFFSET									(WAVE_MAC_A_BASE_ADDR + 0x020AA)		/* 0x20, change */

#define		WAVE_MAC_B_MODE_REG_OFFSET									(WAVE_MAC_B_BASE_ADDR + 0x020AA)		/* 0x20, change */

#define		WAVE_MAC_A_BACKOFF_SEED_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x020AE)		/* 0x03, change */

#define		WAVE_MAC_B_BACKOFF_SEED_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x020AE)		/* 0x03, change */

#define		WAVE_MAC_A_MIN_CW_FOR_AC0_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02102)		/* 0x0F */

#define		WAVE_MAC_B_MIN_CW_FOR_AC0_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02102)		/* 0x0F */

#define		WAVE_MAC_A_MAX_CW_FOR_AC0_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02106)		/* 0x3FF */

#define		WAVE_MAC_B_MAX_CW_FOR_AC0_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02106)		/* 0x3FF */

#define		WAVE_MAC_A_MIN_CW_FOR_AC1_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0210A)		/* 0x07 */

#define		WAVE_MAC_B_MIN_CW_FOR_AC1_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0210A)		/* 0x07 */

#define		WAVE_MAC_A_MAX_CW_FOR_AC1_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0210E)		/* 0x3FF */

#define		WAVE_MAC_B_MAX_CW_FOR_AC1_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0210E)		/* 0x3FF */

#define		WAVE_MAC_A_MIN_CW_FOR_AC2_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02112)		/* 0x03 */

#define		WAVE_MAC_B_MIN_CW_FOR_AC2_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02112)		/* 0x03 */

#define		WAVE_MAC_A_MAX_CW_FOR_AC2_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02116)		/* 0x0F */

#define		WAVE_MAC_B_MAX_CW_FOR_AC2_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02116)		/* 0x0F */

#define		WAVE_MAC_A_MIN_CW_FOR_AC3_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0211A)		/* 0x03 */

#define		WAVE_MAC_B_MIN_CW_FOR_AC3_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0211A)		/* 0x03 */

#define		WAVE_MAC_A_MAX_CW_FOR_AC3_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0211E)		/* 0x07 */

#define		WAVE_MAC_B_MAX_CW_FOR_AC3_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0211E)		/* 0x07 */

#define		WAVE_MAC_A_AIFSN_FOR_AC0_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02122)		/* 0x09 */

#define		WAVE_MAC_B_AIFSN_FOR_AC0_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02122)		/* 0x09 */

#define		WAVE_MAC_A_AIFSN_FOR_AC1_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x02126)		/* 0x06 */

#define		WAVE_MAC_B_AIFSN_FOR_AC1_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x02126)		/* 0x06 */

#define		WAVE_MAC_A_AIFSN_FOR_AC2_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0212A)		/* 0x03 */

#define		WAVE_MAC_B_AIFSN_FOR_AC2_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0212A)		/* 0x03 */

#define		WAVE_MAC_A_AIFSN_FOR_AC3_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x0212E)		/* 0x02 */

#define		WAVE_MAC_B_AIFSN_FOR_AC3_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x0212E)		/* 0x02 */

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP0_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02140)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP0_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02142)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP0_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02140)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP0_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02142)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP1_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02144)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP1_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02146)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP1_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02144)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP1_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02146)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP2_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02148)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP2_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0214A)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP2_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02148)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP2_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0214A)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP3_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0214C)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP3_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0214E)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP3_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0214C)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP3_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0214E)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP4_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02150)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP4_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02152)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP4_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02150)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP4_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02152)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP5_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02154)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP5_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02156)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP5_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02154)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP5_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02156)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP6_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02158)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP6_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0215A)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP6_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02158)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP6_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0215A)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP7_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0215C)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP7_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0215E)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP7_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0215C)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP7_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0215E)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP8_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02160)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP8_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02162)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP8_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02160)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP8_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02162)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP9_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02164)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP9_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02166)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP9_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02164)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP9_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02166)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP10_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02168)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP10_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0216A)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP10_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02168)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP10_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0216A)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP11_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0216C)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP11_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0216E)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP11_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0216C)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP11_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0216E)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP12_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02170)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP12_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02172)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP12_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02170)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP12_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02172)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP13_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02174)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP13_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02176)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP13_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02174)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP13_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02176)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP14_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x02178)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP14_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0217A)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP14_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x02178)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP14_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0217A)

#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP15_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0217C)
#define		WAVE_MAC_A_MIB_TIME_SLOT_BITMAP15_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x0217E)

#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP15_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0217C)
#define		WAVE_MAC_B_MIB_TIME_SLOT_BITMAP15_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x0217E)


#define		WAVE_MAC_A_RSE_CCH_TIME_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02180)		/* 0x1388, change */
#define		WAVE_MAC_A_RSE_CCH_TIME_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02182)		/* 0x1388, change */

#define		WAVE_MAC_B_RSE_CCH_TIME_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02180)		/* 0x1388, change */
#define		WAVE_MAC_B_RSE_CCH_TIME_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02182)		/* 0x1388, change */

#define		WAVE_MAC_A_OBU_CCH_TIME_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02184)		/* 0x4e20 */
#define		WAVE_MAC_A_OBU_CCH_TIME_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02186)		/* 0x4e20 */

#define		WAVE_MAC_B_OBU_CCH_TIME_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02184)		/* 0x4e20 */
#define		WAVE_MAC_B_OBU_CCH_TIME_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02186)		/* 0x4e20 */

#define		WAVE_MAC_A_V2I_SCH_TIME_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02188)		/* 0x11170, change */
#define		WAVE_MAC_A_V2I_SCH_TIME_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0218A)		/* 0x11170, change */

#define		WAVE_MAC_B_V2I_SCH_TIME_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02188)		/* 0x11170, change */
#define		WAVE_MAC_B_V2I_SCH_TIME_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0218A)		/* 0x11170, change */

#define		WAVE_MAC_A_V2V_SCH_TIME_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0218C)		/* 0x0, change */
#define		WAVE_MAC_A_V2V_SCH_TIME_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0218E)		/* 0x0, change */

#define		WAVE_MAC_B_V2V_SCH_TIME_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0218C)		/* 0x0, change */
#define		WAVE_MAC_B_V2V_SCH_TIME_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0218E)		/* 0x0, change */

#define		WAVE_MAC_A_CCH_SCH_CYCLE_TIME_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02190)		/* 0x186a0 */
#define		WAVE_MAC_A_CCH_SCH_CYCLE_TIME_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x02192)		/* 0x186a0 */

#define		WAVE_MAC_B_CCH_SCH_CYCLE_TIME_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02190)		/* 0x186a0 */
#define		WAVE_MAC_B_CCH_SCH_CYCLE_TIME_L_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x02192)		/* 0x186a0 */

#define		WAVE_MAC_A_V2IV_SCH_REPEAT_CYCLE_TIME_H_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x02194)		/* 0x186a0 */
#define		WAVE_MAC_A_V2IV_SCH_REPEAT_CYCLE_TIME_L_REG_OFFSET	(WAVE_MAC_A_BASE_ADDR + 0x02196)		/* 0x186a0 */

#define		WAVE_MAC_B_V2IV_SCH_REPEAT_CYCLE_TIME_H_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x02194)		/* 0x186a0 */
#define		WAVE_MAC_B_V2IV_SCH_REPEAT_CYCLE_TIME_L_REG_OFFSET	(WAVE_MAC_B_BASE_ADDR + 0x02196)		/* 0x186a0 */

#define		WAVE_MAC_A_SYNC_TOLERANCE_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x02198)		/* 0x3e8, change */
#define		WAVE_MAC_A_SYNC_TOLERANCE_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0219A)		/* 0x3e8, change */

#define		WAVE_MAC_B_SYNC_TOLERANCE_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x02198)		/* 0x3e8, change */
#define		WAVE_MAC_B_SYNC_TOLERANCE_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0219A)		/* 0x3e8, change */

#define		WAVE_MAC_A_RF_SWITCH_TIME_H_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0219C)		/* 0x3e8, change */
#define		WAVE_MAC_A_RF_SWITCH_TIME_L_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x0219E)		/* 0x3e8, change */

#define		WAVE_MAC_B_RF_SWITCH_TIME_H_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0219C)		/* 0x3e8, change */
#define		WAVE_MAC_B_RF_SWITCH_TIME_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x0219E)		/* 0x3e8, change */

#define		WAVE_MAC_A_TIME_SLOT_LEN_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021A2)		/* 0x1388 */	

#define		WAVE_MAC_B_TIME_SLOT_LEN_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021A2)		/* 0x1388 */	

#define		WAVE_MAC_A_NUM_OF_TIME_SLOT_FOR_CCH_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x021A6)		/* 0x04, change */

#define		WAVE_MAC_B_NUM_OF_TIME_SLOT_FOR_CCH_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x021A6)		/* 0x04, change */

#define		WAVE_MAC_A_NUM_OF_TIME_SLOT_FOR_V2I_SCH_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x021AA)		/* 0x0e, change */

#define		WAVE_MAC_B_NUM_OF_TIME_SLOT_FOR_V2I_SCH_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x021AA)		/* 0x0e, change */

#define		WAVE_MAC_A_NUM_OF_TIME_SLOT_FOR_V2V_SCH_REG_OFFSET		(WAVE_MAC_A_BASE_ADDR + 0x021AE)		/* 0x0, change */

#define		WAVE_MAC_B_NUM_OF_TIME_SLOT_FOR_V2V_SCH_REG_OFFSET		(WAVE_MAC_B_BASE_ADDR + 0x021AE)		/* 0x0, change */

#define		WAVE_MAC_A_NUM_OF_TIME_SLOT_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021B2)

#define		WAVE_MAC_B_NUM_OF_TIME_SLOT_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021B2)


#define		WAVE_MAC_A_MIB_TX_TIME_MARGINT_H_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x021B4)
#define		WAVE_MAC_A_MIB_TX_TIME_MARGINT_L_REG_OFFSET			(WAVE_MAC_A_BASE_ADDR + 0x021B6)

#define		WAVE_MAC_B_MIB_TX_TIME_MARGINT_H_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x021B4)
#define		WAVE_MAC_B_MIB_TX_TIME_MARGINT_L_REG_OFFSET			(WAVE_MAC_B_BASE_ADDR + 0x021B6)

#define		WAVE_MAC_A_MIB_TX_POWER_RSP_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x021BA)

#define		WAVE_MAC_B_MIB_TX_POWER_RSP_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x021BA)


#define		WAVE_MAC_A_TSF_HTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021C0)		/* 0x0 */
#define		WAVE_MAC_A_TSF_HTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021C2)		/* 0x0 */

#define		WAVE_MAC_B_TSF_HTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021C0)		/* 0x0 */
#define		WAVE_MAC_B_TSF_HTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021C2)		/* 0x0 */

#define		WAVE_MAC_A_TSF_LTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021C4)		/* 0x0 */
#define		WAVE_MAC_A_TSF_LTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021C6)		/* 0x0 */

#define		WAVE_MAC_B_TSF_LTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021C4)		/* 0x0 */
#define		WAVE_MAC_B_TSF_LTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021C6)		/* 0x0 */

#define		WAVE_MAC_A_RX_HTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021C8)		/* 0x0 */
#define		WAVE_MAC_A_RX_HTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021CA)		/* 0x0 */

#define		WAVE_MAC_B_RX_HTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021C8)		/* 0x0 */
#define		WAVE_MAC_B_RX_HTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021CA)		/* 0x0 */

#define		WAVE_MAC_A_RX_LTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021CC)		/* 0x0 */
#define		WAVE_MAC_A_RX_LTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021CE)		/* 0x0 */

#define		WAVE_MAC_B_RX_LTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021CC)		/* 0x0 */
#define		WAVE_MAC_B_RX_LTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021CE)		/* 0x0 */

#define		WAVE_MAC_A_TX_HTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021D0)		/* 0x0 */
#define		WAVE_MAC_A_TX_HTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021D2)		/* 0x0 */

#define		WAVE_MAC_B_TX_HTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021D0)		/* 0x0 */
#define		WAVE_MAC_B_TX_HTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021D2)		/* 0x0 */

#define		WAVE_MAC_A_TX_LTIMER_H_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021D4)		/* 0x0 */
#define		WAVE_MAC_A_TX_LTIMER_L_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021D6)		/* 0x0 */

#define		WAVE_MAC_B_TX_LTIMER_H_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021D4)		/* 0x0 */
#define		WAVE_MAC_B_TX_LTIMER_L_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021D6)		/* 0x0 */

#define		WAVE_MAC_A_TSF_UPDATE_RANGE_H_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x021D8)
#define		WAVE_MAC_A_TSF_UPDATE_RANGE_L_REG_OFFSET				(WAVE_MAC_A_BASE_ADDR + 0x021DA)

#define		WAVE_MAC_B_TSF_UPDATE_RANGE_H_REG_OFFSET				(WAVE_MAC_B_BASE_ADDR + 0x021D8)
#define		WAVE_MAC_B_TSF_UPDATE_RANGE_L_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021DA)

#define		WAVE_MAC_A_TSF_RX_DELAY_REG_OFFSET						(WAVE_MAC_A_BASE_ADDR + 0x021DE)

#define		WAVE_MAC_B_TSF_RX_DELAY_REG_OFFSET						(WAVE_MAC_B_BASE_ADDR + 0x021DE)

#define		WAVE_MAC_A_TSF_TX_DELAY_3M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021E2)

#define		WAVE_MAC_B_TSF_TX_DELAY_3M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021E2)

#define		WAVE_MAC_A_TSF_TX_DELAY_45M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021E6)

#define		WAVE_MAC_B_TSF_TX_DELAY_45M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021E6)

#define		WAVE_MAC_A_TSF_TX_DELAY_6M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021EA)

#define		WAVE_MAC_B_TSF_TX_DELAY_6M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021EA)

#define		WAVE_MAC_A_TSF_TX_DELAY_9M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021EE)

#define		WAVE_MAC_B_TSF_TX_DELAY_9M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021EE)

#define		WAVE_MAC_A_TSF_TX_DELAY_12M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021F2)

#define		WAVE_MAC_B_TSF_TX_DELAY_12M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021F2)

#define		WAVE_MAC_A_TSF_TX_DELAY_18M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021F6)

#define		WAVE_MAC_B_TSF_TX_DELAY_18M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021F6)

#define		WAVE_MAC_A_TSF_TX_DELAY_24M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021FA)

#define		WAVE_MAC_B_TSF_TX_DELAY_24M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021FA)

#define		WAVE_MAC_A_TSF_TX_DELAY_27M_REG_OFFSET					(WAVE_MAC_A_BASE_ADDR + 0x021FE)

#define		WAVE_MAC_B_TSF_TX_DELAY_27M_REG_OFFSET					(WAVE_MAC_B_BASE_ADDR + 0x021FE)



/* Modem Register Define */
#define		WAVE_MODEM_A_PK_ON_THRESHOLD_COUNTER_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00002)		/* 0x132 */
#define		WAVE_MODEM_B_PK_ON_THRESHOLD_COUNTER_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00002)		/* 0x132 */

#define		WAVE_MODEM_A_PK_OFF_THRESHOLD_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00006)			/* 0xfa00 */
#define		WAVE_MODEM_B_PK_OFF_THRESHOLD_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00006)			/* 0xfa00 */

#define		WAVE_MODEM_A_PK_LOST_COUNT_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0000A)			/* 0x800  */
#define		WAVE_MODEM_B_PK_LOST_COUNT_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0000A)			/* 0x800  */

#define		WAVE_MODEM_A_RF_LNA_GAIN_LOW_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0000E)			/* 0x45 */
#define		WAVE_MODEM_B_RF_LNA_GAIN_LOW_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0000E)			/* 0x45 */

#define		WAVE_MODEM_A_RF_GAIN_SET_TIME_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00012)		/* 0x45 */
#define		WAVE_MODEM_B_RF_GAIN_SET_TIME_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00012)		/* 0x45 */

#define		WAVE_MODEM_A_RF_DEFAULT_GAIN_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00016)		/* 0x7ff */
#define		WAVE_MODEM_B_RF_DEFAULT_GAIN_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00016)		/* 0x7ff */

#define		WAVE_MODEM_A_MODE_SELECT_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0001A)			/* 0x20c0 */
#define		WAVE_MODEM_B_MODE_SELECT_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0001A)			/* 0x20c0 */

#define		WAVE_MODEM_A_TX_SCALE_SCRAMBLE_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0001E)			/* 0x1dd */
#define		WAVE_MODEM_B_TX_SCALE_SCRAMBLE_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0001E)			/* 0x1dd */

#define		WAVE_MODEM_A_SERVICE_FIELD_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00022)			/* 0x0 */
#define		WAVE_MODEM_B_SERVICE_FIELD_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00022)			/* 0x0 */

#define		WAVE_MODEM_A_RSSI0_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x00026)			/* 0x245 */
#define		WAVE_MODEM_B_RSSI0_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x00026)			/* 0x245 */

#define		WAVE_MODEM_A_RSSI1_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x0002A)			/* 0x3838 */
#define		WAVE_MODEM_B_RSSI1_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x0002A)			/* 0x3838 */

#define		WAVE_MODEM_A_EXT_LNA_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x0002E)
#define		WAVE_MODEM_B_EXT_LNA_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x0002E)

#define		WAVE_MODEM_A_FTO_THRESHOLD_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00032)
#define		WAVE_MODEM_B_FTO_THRESHOLD_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00032)	

#define		WAVE_MODEM_A_HANDOVER_RF_CH1_ID_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00036)
#define		WAVE_MODEM_B_HANDOVER_RF_CH1_ID_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x00036)

#define		WAVE_MODEM_A_HANDOVER_RF_CH1_IF_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x0003A)
#define		WAVE_MODEM_B_HANDOVER_RF_CH1_IF_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x0003A)

#define		WAVE_MODEM_A_HANDOVER_RF_CH2_ID_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x0003E)
#define		WAVE_MODEM_B_HANDOVER_RF_CH2_ID_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x0003E)

#define		WAVE_MODEM_A_HANDOVER_RF_CH2_IF_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00042)
#define		WAVE_MODEM_B_HANDOVER_RF_CH2_IF_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00042)

#define		WAVE_MODEM_A_HANDOVER_RF_CH3_ID_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00046)
#define		WAVE_MODEM_B_HANDOVER_RF_CH3_ID_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x00046)

#define		WAVE_MODEM_A_HANDOVER_RF_CH3_IF_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x0004A)
#define		WAVE_MODEM_B_HANDOVER_RF_CH3_IF_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x0004A)

#define		WAVE_MODEM_A_TX_PWR_SET1_2_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0004E)
#define		WAVE_MODEM_B_TX_PWR_SET1_2_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0004E)

#define		WAVE_MODEM_A_TX_PWR_SET3_4_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00052)
#define		WAVE_MODEM_B_TX_PWR_SET3_4_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00052)

#define		WAVE_MODEM_A_TX_PWR_SET5_6_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00056)
#define		WAVE_MODEM_B_TX_PWR_SET5_6_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00056)

#define		WAVE_MODEM_A_TX_PWR_SET7_8_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0005A)
#define		WAVE_MODEM_B_TX_PWR_SET7_8_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0005A)

#define		WAVE_MODEM_A_ETC_REG_OFFSET								(WAVE_MODEM_A_BASE_ADDR + 0x0005E)
#define		WAVE_MODEM_B_ETC_REG_OFFSET								(WAVE_MODEM_B_BASE_ADDR + 0x0005E)

#define		WAVE_MODEM_A_TEST_SEL_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x00062)
#define		WAVE_MODEM_B_TEST_SEL_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x00062)

#define		WAVE_MODEM_A_RSSI_REG2_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x00066)
#define		WAVE_MODEM_B_RSSI_REG2_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x00066)

#define		WAVE_MODEM_A_AGC_REG3_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0006A)
#define		WAVE_MODEM_B_AGC_REG3_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0006A)

#define		WAVE_MODEM_A_RF_STATE_CTRL_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0006E)
#define		WAVE_MODEM_B_RF_STATE_CTRL_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0006E)

#define		WAVE_MODEM_A_RF_SPI_CTRL_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x00072)
#define		WAVE_MODEM_B_RF_SPI_CTRL_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x00072)

#define		WAVE_MODEM_A_MAX2829_DATA0_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00076)
#define		WAVE_MODEM_B_MAX2829_DATA0_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00076)

#define		WAVE_MODEM_A_MAX2829_DATA1_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0007A)
#define		WAVE_MODEM_B_MAX2829_DATA1_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0007A)

#define		WAVE_MODEM_A_MAX2829_DATA2_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0007E)
#define		WAVE_MODEM_B_MAX2829_DATA2_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0007E)

#define		WAVE_MODEM_A_MAX2829_DATA3_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00082)
#define		WAVE_MODEM_B_MAX2829_DATA3_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00082)

#define		WAVE_MODEM_A_MAX2829_DATA4_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00086)
#define		WAVE_MODEM_B_MAX2829_DATA4_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00086)

#define		WAVE_MODEM_A_MAX2829_DATA5_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0008A)
#define		WAVE_MODEM_B_MAX2829_DATA5_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0008A)

#define		WAVE_MODEM_A_MAX2829_DATA6_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0008E)
#define		WAVE_MODEM_B_MAX2829_DATA6_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0008E)

#define		WAVE_MODEM_A_MAX2829_DATA7_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00092)
#define		WAVE_MODEM_B_MAX2829_DATA7_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00092)

#define		WAVE_MODEM_A_MAX2829_DATA8_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00096)
#define		WAVE_MODEM_B_MAX2829_DATA8_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00096)

#define		WAVE_MODEM_A_MAX2829_DATA9_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0009A)
#define		WAVE_MODEM_B_MAX2829_DATA9_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0009A)

#define		WAVE_MODEM_A_MAX2829_DATA10_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0009E)
#define		WAVE_MODEM_B_MAX2829_DATA10_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0009E)

#define		WAVE_MODEM_A_MAX2829_DATA11_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000A2)
#define		WAVE_MODEM_B_MAX2829_DATA11_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000A2)

#define		WAVE_MODEM_A_MAX2829_DATA12_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000A6)
#define		WAVE_MODEM_B_MAX2829_DATA12_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000A6)

#define		WAVE_MODEM_A_RF_DIFF_GAIN01_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000AA)
#define		WAVE_MODEM_B_RF_DIFF_GAIN01_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000AA)

#define		WAVE_MODEM_A_RF_DIFF_GAIN02_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000AE)
#define		WAVE_MODEM_B_RF_DIFF_GAIN02_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000AE)

#define		WAVE_MODEM_A_RF_DIFF_GAIN03_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000B2)
#define		WAVE_MODEM_B_RF_DIFF_GAIN03_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000B2)

#define		WAVE_MODEM_A_RF_DIFF_GAIN04_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000B6)
#define		WAVE_MODEM_B_RF_DIFF_GAIN04_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000B6)

#define		WAVE_MODEM_A_RF_DIFF_GAIN05_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000BA)
#define		WAVE_MODEM_B_RF_DIFF_GAIN05_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000BA)	

#define		WAVE_MODEM_A_RF_DIFF_GAIN06_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000BE)
#define		WAVE_MODEM_B_RF_DIFF_GAIN06_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000BE)

#define		WAVE_MODEM_A_RF_DIFF_GAIN07_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000C2)
#define		WAVE_MODEM_B_RF_DIFF_GAIN07_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000C2)

#define		WAVE_MODEM_A_RF_DIFF_GAIN08_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000C6)
#define		WAVE_MODEM_B_RF_DIFF_GAIN08_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000C6)

#define		WAVE_MODEM_A_RF_DIFF_GAIN09_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000CA)
#define		WAVE_MODEM_B_RF_DIFF_GAIN09_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000CA)

#define		WAVE_MODEM_A_RF_DIFF_GAIN10_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000CE)
#define		WAVE_MODEM_B_RF_DIFF_GAIN10_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000CE)

#define		WAVE_MODEM_A_RF_DIFF_GAIN11_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000D2)
#define		WAVE_MODEM_B_RF_DIFF_GAIN11_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000D2)	

#define		WAVE_MODEM_A_RF_DIFF_GAIN12_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000D6)
#define		WAVE_MODEM_B_RF_DIFF_GAIN12_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000D6)

#define		WAVE_MODEM_A_RF_DIFF_GAIN13_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000DA)
#define		WAVE_MODEM_B_RF_DIFF_GAIN13_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000DA)

#define		WAVE_MODEM_A_RF_DIFF_GAIN14_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000DE)
#define		WAVE_MODEM_B_RF_DIFF_GAIN14_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000DE)

#define		WAVE_MODEM_A_RF_DIFF_GAIN15_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000E2)
#define		WAVE_MODEM_B_RF_DIFF_GAIN15_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000E2)


#define		WAVE_MODEM_A_CH_NUM_LOCK_RMS_PWR_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x000E6)	
#define		WAVE_MODEM_B_CH_NUM_LOCK_RMS_PWR_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x000E6)

#define		WAVE_MODEM_A_RX_SCRAMBLE_SEED_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x000EA)
#define		WAVE_MODEM_B_RX_SCRAMBLE_SEED_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x000EA)

#define		WAVE_MODEM_A_0_SIGNAL_FIELD_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000EE)
#define		WAVE_MODEM_B_0_SIGNAL_FIELD_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000EE)

#define		WAVE_MODEM_A_PHY_ERR0_CNT_H_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000F2)
#define		WAVE_MODEM_B_PHY_ERR0_CNT_H_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000F2)

#define		WAVE_MODEM_A_PHY_ERR0_CNT_L_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000F6)
#define		WAVE_MODEM_B_PHY_ERR0_CNT_L_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000F6)

#define		WAVE_MODEM_A_PHY_ERR1_CNT_H_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000FA)
#define		WAVE_MODEM_B_PHY_ERR1_CNT_H_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000FA)

#define		WAVE_MODEM_A_PHY_ERR1_CNT_L_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x000FE)	
#define		WAVE_MODEM_B_PHY_ERR1_CNT_L_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x000FE)

#define		WAVE_MODEM_A_PHY_ERR2_CNT_H_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00102)
#define		WAVE_MODEM_B_PHY_ERR2_CNT_H_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00102)

#define		WAVE_MODEM_A_PHY_ERR2_CNT_L_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00106)
#define		WAVE_MODEM_B_PHY_ERR2_CNT_L_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00106)

#define		WAVE_MODEM_A_PHY_ERR3_CNT_H_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0010A)
#define		WAVE_MODEM_B_PHY_ERR3_CNT_H_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0010A)

#define		WAVE_MODEM_A_PHY_ERR3_CNT_L_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0010E)
#define		WAVE_MODEM_B_PHY_ERR3_CNT_L_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0010E)

#define		WAVE_MODEM_A_VERSION_ID0_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x00112)
#define		WAVE_MODEM_B_VERSION_ID0_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x00112)

#define		WAVE_MODEM_A_VERSION_ID1_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x00116)
#define		WAVE_MODEM_B_VERSION_ID1_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x00116)

#define		WAVE_MODEM_A_VERSION_ID2_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0011A)
#define		WAVE_MODEM_B_VERSION_ID2_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0011A)

#define		WAVE_MODEM_A_VERSION_H_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x0011E)
#define		WAVE_MODEM_B_VERSION_H_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x0011E)

#define		WAVE_MODEM_A_VERSION_L_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x00122)
#define		WAVE_MODEM_B_VERSION_L_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x00122)

#define		WAVE_MODEM_A_RF_DIFF_GAIN16_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00126)
#define		WAVE_MODEM_B_RF_DIFF_GAIN16_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00126)

#define		WAVE_MODEM_A_RF_DIFF_GAIN17_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0012A)
#define		WAVE_MODEM_B_RF_DIFF_GAIN17_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0012A)

#define		WAVE_MODEM_A_AGC_REG4_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x0012E)
#define		WAVE_MODEM_B_AGC_REG4_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x0012E)

#define		WAVE_MODEM_A_AGC_REG5_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x00132)
#define		WAVE_MODEM_B_AGC_REG5_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x00132)

#define		WAVE_MODEM_A_AGC_REG6_REG_OFFSET							(WAVE_MODEM_A_BASE_ADDR + 0x00136)
#define		WAVE_MODEM_B_AGC_REG6_REG_OFFSET							(WAVE_MODEM_B_BASE_ADDR + 0x00136)

#define		WAVE_MODEM_A_CCA_ON_OFF_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0013A)
#define		WAVE_MODEM_B_CCA_ON_OFF_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0013A)

#define		WAVE_MODEM_A_HANDOVER_5_85_ID_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0013E)
#define		WAVE_MODEM_B_HANDOVER_5_85_ID_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0013E)

#define		WAVE_MODEM_A_HANDOVER_5_85_IF_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00142)
#define		WAVE_MODEM_B_HANDOVER_5_85_IF_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00142)

#define		WAVE_MODEM_A_HANDOVER_5_86_ID_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00146)
#define		WAVE_MODEM_B_HANDOVER_5_86_ID_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00146)

#define		WAVE_MODEM_A_HANDOVER_5_86_IF_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0014A)
#define		WAVE_MODEM_B_HANDOVER_5_86_IF_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0014A)

#define		WAVE_MODEM_A_HANDOVER_5_87_ID_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0014E)
#define		WAVE_MODEM_B_HANDOVER_5_87_ID_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0014E)

#define		WAVE_MODEM_A_HANDOVER_5_87_IF_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00152)
#define		WAVE_MODEM_B_HANDOVER_5_87_IF_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00152)

#define		WAVE_MODEM_A_HANDOVER_5_88_ID_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00156)
#define		WAVE_MODEM_B_HANDOVER_5_88_ID_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00156)

#define		WAVE_MODEM_A_HANDOVER_5_88_IF_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0015A)
#define		WAVE_MODEM_B_HANDOVER_5_88_IF_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0015A)

#define		WAVE_MODEM_A_MATCHED_FILTER_0_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0015E)
#define		WAVE_MODEM_B_MATCHED_FILTER_0_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0015E)

#define		WAVE_MODEM_A_MATCHED_FILTER_1_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00162)
#define		WAVE_MODEM_B_MATCHED_FILTER_1_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00162)

#define		WAVE_MODEM_A_MATCHED_FILTER_2_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00166)
#define		WAVE_MODEM_B_MATCHED_FILTER_2_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00166)

#define		WAVE_MODEM_A_MATCHED_FILTER_3_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0016A)
#define		WAVE_MODEM_B_MATCHED_FILTER_3_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0016A)

#define		WAVE_MODEM_A_MATCHED_FILTER_4_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0016E)
#define		WAVE_MODEM_B_MATCHED_FILTER_4_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0016E)

#define		WAVE_MODEM_A_MATCHED_FILTER_5_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00172)
#define		WAVE_MODEM_B_MATCHED_FILTER_5_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00172)

#define		WAVE_MODEM_A_MATCHED_FILTER_6_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00176)
#define		WAVE_MODEM_B_MATCHED_FILTER_6_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00176)

#define		WAVE_MODEM_A_MATCHED_FILTER_7_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0017A)
#define		WAVE_MODEM_B_MATCHED_FILTER_7_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0017A)

#define		WAVE_MODEM_A_MATCHED_FILTER_8_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0017E)
#define		WAVE_MODEM_B_MATCHED_FILTER_8_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0017E)

#define		WAVE_MODEM_A_MATCHED_FILTER_9_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00182)
#define		WAVE_MODEM_B_MATCHED_FILTER_9_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00182)

#define		WAVE_MODEM_A_MATCHED_FILTER_10_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00186)
#define		WAVE_MODEM_B_MATCHED_FILTER_10_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00186)

#define		WAVE_MODEM_A_MATCHED_FILTER_11_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0018A)
#define		WAVE_MODEM_B_MATCHED_FILTER_11_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0018A)

#define		WAVE_MODEM_A_MATCHED_FILTER_12_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0018E)
#define		WAVE_MODEM_B_MATCHED_FILTER_12_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0018E)

#define		WAVE_MODEM_A_MATCHED_FILTER_13_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00192)
#define		WAVE_MODEM_B_MATCHED_FILTER_13_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00192)

#define		WAVE_MODEM_A_MATCHED_FILTER_14_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00196)
#define		WAVE_MODEM_B_MATCHED_FILTER_14_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00196)

#define		WAVE_MODEM_A_MATCHED_FILTER_15_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0019A)
#define		WAVE_MODEM_B_MATCHED_FILTER_15_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0019A)

#define		WAVE_MODEM_A_MATCHED_FILTER_16_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0019E)
#define		WAVE_MODEM_B_MATCHED_FILTER_16_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0019E)

#define		WAVE_MODEM_A_MATCHED_FILTER_17_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001A2)
#define		WAVE_MODEM_B_MATCHED_FILTER_17_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001A2)

#define		WAVE_MODEM_A_MATCHED_FILTER_18_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001A6)
#define		WAVE_MODEM_B_MATCHED_FILTER_18_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001A6)

#define		WAVE_MODEM_A_MATCHED_FILTER_19_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001AA)
#define		WAVE_MODEM_B_MATCHED_FILTER_19_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001AA)

#define		WAVE_MODEM_A_MATCHED_FILTER_20_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001AE)
#define		WAVE_MODEM_B_MATCHED_FILTER_20_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001AE)

#define		WAVE_MODEM_A_MATCHED_FILTER_21_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001B2)
#define		WAVE_MODEM_B_MATCHED_FILTER_21_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001B2)

#define		WAVE_MODEM_A_MATCHED_FILTER_22_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001B6)
#define		WAVE_MODEM_B_MATCHED_FILTER_22_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001B6)

#define		WAVE_MODEM_A_MATCHED_FILTER_23_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001BA)
#define		WAVE_MODEM_B_MATCHED_FILTER_23_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001BA)

#define		WAVE_MODEM_A_MATCHED_FILTER_24_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001BE)
#define		WAVE_MODEM_B_MATCHED_FILTER_24_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001BE)

#define		WAVE_MODEM_A_MATCHED_FILTER_25_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001C2)
#define		WAVE_MODEM_B_MATCHED_FILTER_25_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001C2)

#define		WAVE_MODEM_A_MATCHED_FILTER_26_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001C6)
#define		WAVE_MODEM_B_MATCHED_FILTER_26_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001C6)

#define		WAVE_MODEM_A_MATCHED_FILTER_27_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001CA)
#define		WAVE_MODEM_B_MATCHED_FILTER_27_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001CA)

#define		WAVE_MODEM_A_MATCHED_FILTER_28_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001CE)
#define		WAVE_MODEM_B_MATCHED_FILTER_28_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001CE)

#define		WAVE_MODEM_A_MATCHED_FILTER_29_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001D2)
#define		WAVE_MODEM_B_MATCHED_FILTER_29_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001D2)

#define		WAVE_MODEM_A_MATCHED_FILTER_30_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001D6)
#define		WAVE_MODEM_B_MATCHED_FILTER_30_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001D6)

#define		WAVE_MODEM_A_MATCHED_FILTER_31_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001DA)
#define		WAVE_MODEM_B_MATCHED_FILTER_31_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001DA)

#define		WAVE_MODEM_A_MATCHED_FILTER_32_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x001DE)
#define		WAVE_MODEM_B_MATCHED_FILTER_32_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x001DE)

#define		WAVE_MODEM_A_CH_EST_FILTER_00_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001E2)
#define		WAVE_MODEM_B_CH_EST_FILTER_00_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001E2)

#define		WAVE_MODEM_A_CH_EST_FILTER_01_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001E6)
#define		WAVE_MODEM_B_CH_EST_FILTER_01_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001E6)

#define		WAVE_MODEM_A_CH_EST_FILTER_02_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001EA)
#define		WAVE_MODEM_B_CH_EST_FILTER_02_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001EA)

#define		WAVE_MODEM_A_CH_EST_FILTER_03_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001EE)
#define		WAVE_MODEM_B_CH_EST_FILTER_03_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001EE)

#define		WAVE_MODEM_A_CH_EST_FILTER_04_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001F2)
#define		WAVE_MODEM_B_CH_EST_FILTER_04_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001F2)

#define		WAVE_MODEM_A_CH_EST_FILTER_05_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001F6)
#define		WAVE_MODEM_B_CH_EST_FILTER_05_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001F6)

#define		WAVE_MODEM_A_CH_EST_FILTER_06_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001FA)
#define		WAVE_MODEM_B_CH_EST_FILTER_06_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001FA)

#define		WAVE_MODEM_A_CH_EST_FILTER_07_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x001FE)
#define		WAVE_MODEM_B_CH_EST_FILTER_07_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x001FE)

#define		WAVE_MODEM_A_CH_EST_FILTER_08_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00202)
#define		WAVE_MODEM_B_CH_EST_FILTER_08_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00202)

#define		WAVE_MODEM_A_CH_EST_FILTER_09_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00206)
#define		WAVE_MODEM_B_CH_EST_FILTER_09_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00206)

#define		WAVE_MODEM_A_CH_EST_FILTER_10_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0020A)
#define		WAVE_MODEM_B_CH_EST_FILTER_10_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0020A)

#define		WAVE_MODEM_A_CH_EST_FILTER_11_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0020E)
#define		WAVE_MODEM_B_CH_EST_FILTER_11_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0020E)

#define		WAVE_MODEM_A_CH_EST_FILTER_12_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00212)
#define		WAVE_MODEM_B_CH_EST_FILTER_12_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00212)

#define		WAVE_MODEM_A_CH_EST_FILTER_13_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00216)
#define		WAVE_MODEM_B_CH_EST_FILTER_13_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00216)

#define		WAVE_MODEM_A_CH_EST_FILTER_14_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0021A)
#define		WAVE_MODEM_B_CH_EST_FILTER_14_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0021A)

#define		WAVE_MODEM_A_CH_EST_FILTER_15_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0021E)
#define		WAVE_MODEM_B_CH_EST_FILTER_15_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0021E)

#define		WAVE_MODEM_A_CH_EST_FILTER_16_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00222)
#define		WAVE_MODEM_B_CH_EST_FILTER_16_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00222)

#define		WAVE_MODEM_A_CH_EST_FILTER_17_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00226)
#define		WAVE_MODEM_B_CH_EST_FILTER_17_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00226)

#define		WAVE_MODEM_A_CH_EST_FILTER_18_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0022A)
#define		WAVE_MODEM_B_CH_EST_FILTER_18_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0022A)

#define		WAVE_MODEM_A_CH_EST_FILTER_19_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0022E)
#define		WAVE_MODEM_B_CH_EST_FILTER_19_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0022E)

#define		WAVE_MODEM_A_CH_EST_FILTER_20_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00232)
#define		WAVE_MODEM_B_CH_EST_FILTER_20_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00232)

#define		WAVE_MODEM_A_CH_EST_FILTER_21_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00236)
#define		WAVE_MODEM_B_CH_EST_FILTER_21_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00236)

#define		WAVE_MODEM_A_CH_EST_FILTER_22_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0023A)
#define		WAVE_MODEM_B_CH_EST_FILTER_22_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0023A)

#define		WAVE_MODEM_A_CH_EST_FILTER_23_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0023E)
#define		WAVE_MODEM_B_CH_EST_FILTER_23_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0023E)

#define		WAVE_MODEM_A_CH_EST_FILTER_24_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00242)
#define		WAVE_MODEM_B_CH_EST_FILTER_24_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00242)

#define		WAVE_MODEM_A_CH_EST_FILTER_25_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00246)
#define		WAVE_MODEM_B_CH_EST_FILTER_25_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00246)

#define		WAVE_MODEM_A_CH_EST_FILTER_26_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0024A)
#define		WAVE_MODEM_B_CH_EST_FILTER_26_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0024A)

#define		WAVE_MODEM_A_CH_EST_FILTER_27_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0024E)
#define		WAVE_MODEM_B_CH_EST_FILTER_27_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0024E)

#define		WAVE_MODEM_A_CH_EST_FILTER_28_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00252)
#define		WAVE_MODEM_B_CH_EST_FILTER_28_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00252)

#define		WAVE_MODEM_A_CH_EST_FILTER_29_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00256)
#define		WAVE_MODEM_B_CH_EST_FILTER_29_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00256)

#define		WAVE_MODEM_A_CH_EST_FILTER_30_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0025A)
#define		WAVE_MODEM_B_CH_EST_FILTER_30_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0025A)

#define		WAVE_MODEM_A_CH_EST_FILTER_31_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0025E)
#define		WAVE_MODEM_B_CH_EST_FILTER_31_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0025E)

#define		WAVE_MODEM_A_CH_EST_FILTER_32_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00262)
#define		WAVE_MODEM_B_CH_EST_FILTER_32_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00262)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_00_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00266)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_00_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00266)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_01_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0026A)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_01_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0026A)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_02_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0026E)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_02_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0026E)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_03_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00272)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_03_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00272)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_04_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00276)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_04_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00276)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_05_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0027A)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_05_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0027A)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_06_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0027E)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_06_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0027E)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_07_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00282)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_07_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00282)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_08_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00286)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_08_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00286)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_09_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0028A)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_09_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0028A)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_10_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0028E)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_10_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0028E)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_11_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00292)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_11_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00292)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_12_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00296)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_12_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00296)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_13_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0029A)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_13_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0029A)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_14_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0029E)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_14_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0029E)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_15_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x002A2)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_15_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x002A2)

#define		WAVE_MODEM_A_FFT_IFFT_BASIS_VECTOR_16_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x002A6)
#define		WAVE_MODEM_B_FFT_IFFT_BASIS_VECTOR_16_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x002A6)

#define		WAVE_MODEM_A_CONST_MAP_BSPSK_N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002AA)
#define		WAVE_MODEM_B_CONST_MAP_BSPSK_N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002AA)

#define		WAVE_MODEM_A_CONST_MAP_BSPSK_P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002AE)
#define		WAVE_MODEM_B_CONST_MAP_BSPSK_P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002AE)

#define		WAVE_MODEM_A_CONST_MAP_QSPSK_N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002B2)
#define		WAVE_MODEM_B_CONST_MAP_QSPSK_N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002B2)

#define		WAVE_MODEM_A_CONST_MAP_QSPSK_P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002B6)
#define		WAVE_MODEM_B_CONST_MAP_QSPSK_P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002B6)

#define		WAVE_MODEM_A_CONST_MAP_16QAM_3N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002BA)
#define		WAVE_MODEM_B_CONST_MAP_16QAM_3N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002BA)

#define		WAVE_MODEM_A_CONST_MAP_16QAM_1N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002BE)
#define		WAVE_MODEM_B_CONST_MAP_16QAM_1N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002BE)

#define		WAVE_MODEM_A_CONST_MAP_16QAM_1P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002C2)
#define		WAVE_MODEM_B_CONST_MAP_16QAM_1P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002C2)

#define		WAVE_MODEM_A_CONST_MAP_16QAM_3P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002C6)
#define		WAVE_MODEM_B_CONST_MAP_16QAM_3P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002C6)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_7N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002CA)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_7N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002CA)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_5N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002CE)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_5N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002CE)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_3N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002D2)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_3N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002D2)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_1N_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002D6)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_1N_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002D6)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_1P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002DA)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_1P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002DA)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_3P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002DE)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_3P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002DE)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_5P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002E2)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_5P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002E2)

#define		WAVE_MODEM_A_CONST_MAP_64QAM_7P_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002E6)
#define		WAVE_MODEM_B_CONST_MAP_64QAM_7P_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002E6)

#define		WAVE_MODEM_A_THRESHOLD_SIGNAL_POWER_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x002EA)
#define		WAVE_MODEM_B_THRESHOLD_SIGNAL_POWER_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x002EA)

#define		WAVE_MODEM_A_MIDAMBLE_DURATION_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002EE)
#define		WAVE_MODEM_B_MIDAMBLE_DURATION_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002EE)

#define		WAVE_MODEM_A_MAX_FTO_CORRELATION_H_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x002F2)
#define		WAVE_MODEM_B_MAX_FTO_CORRELATION_H_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x002F2)

#define		WAVE_MODEM_A_MAX_FTO_CORRELATION_L_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x002F6)
#define		WAVE_MODEM_B_MAX_FTO_CORRELATION_L_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x002F6)

#define		WAVE_MODEM_A_MIDAMBLE_THRESHOLD_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x002FA)
#define		WAVE_MODEM_B_MIDAMBLE_THRESHOLD_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x002FA)

#define		WAVE_MODEM_A_FFO_ANGEL_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x002FE)
#define		WAVE_MODEM_B_FFO_ANGEL_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x002FE)

#define		WAVE_MODEM_A_MAX_CTO_CORRELATION_H_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00302)
#define		WAVE_MODEM_B_MAX_CTO_CORRELATION_H_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x00302)

#define		WAVE_MODEM_A_MAX_CTO_CORRELATION_L_REG_OFFSET			(WAVE_MODEM_A_BASE_ADDR + 0x00306)
#define		WAVE_MODEM_B_MAX_CTO_CORRELATION_L_REG_OFFSET			(WAVE_MODEM_B_BASE_ADDR + 0x00306)

#define		WAVE_MODEM_A_CFO_ANGEL_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0030A)
#define		WAVE_MODEM_B_CFO_ANGEL_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0030A)


#define		WAVE_MODEM_A_PACKET_DET_COUNT_H_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0030E)
#define		WAVE_MODEM_B_PACKET_DET_COUNT_H_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0030E)

#define		WAVE_MODEM_A_PACKET_DET_COUNT_L_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00312)
#define		WAVE_MODEM_B_PACKET_DET_COUNT_L_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00312)

#define		WAVE_MODEM_A_AGC_COMP_COUNT_H_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00316)
#define		WAVE_MODEM_B_AGC_COMP_COUNT_H_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00316)

#define		WAVE_MODEM_A_AGC_COMP_COUNT_L_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0031A)
#define		WAVE_MODEM_B_AGC_COMP_COUNT_L_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0031A)

#define		WAVE_MODEM_A_DECIMATION_COMP_COUNT_H_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x0031E)
#define		WAVE_MODEM_B_DECIMATION_COMP_COUNT_H_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x0031E)

#define		WAVE_MODEM_A_DECIMATION_COMP_COUNT_L_REG_OFFSET		(WAVE_MODEM_A_BASE_ADDR + 0x00322)
#define		WAVE_MODEM_B_DECIMATION_COMP_COUNT_L_REG_OFFSET		(WAVE_MODEM_B_BASE_ADDR + 0x00322)

#define		WAVE_MODEM_A_SYMBOL_DET_COUNT_H_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00326)
#define		WAVE_MODEM_B_SYMBOL_DET_COUNT_H_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00326)

#define		WAVE_MODEM_A_SYMBOL_DET_COUNT_L_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0032A)
#define		WAVE_MODEM_B_SYMBOL_DET_COUNT_L_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0032A)

#define		WAVE_MODEM_A_CCA_BUSY_COUNT_H_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0032E)
#define		WAVE_MODEM_B_CCA_BUSY_COUNT_H_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0032E)

#define		WAVE_MODEM_A_CCA_BUSY_COUNT_L_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00332)
#define		WAVE_MODEM_B_CCA_BUSY_COUNT_L_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00332)

#define		WAVE_MODEM_A_DEMAP_PWR_BPSK_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00336)
#define		WAVE_MODEM_B_DEMAP_PWR_BPSK_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00336)

#define		WAVE_MODEM_A_DEMAP_PWR_QPSK_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0033A)
#define		WAVE_MODEM_B_DEMAP_PWR_QPSK_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0033A)

#define		WAVE_MODEM_A_DEMAP_PWR_16QAM_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0033E)
#define		WAVE_MODEM_B_DEMAP_PWR_16QAM_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0033E)

#define		WAVE_MODEM_A_DEMAP_PWR_64QAM_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00342)
#define		WAVE_MODEM_B_DEMAP_PWR_64QAM_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00342)

#define		WAVE_MODEM_A_DEMAP_COEF_2_3_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x00346)
#define		WAVE_MODEM_B_DEMAP_COEF_2_3_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x00346)

#define		WAVE_MODEM_A_DEMAP_COEF_4_7_REG_OFFSET					(WAVE_MODEM_A_BASE_ADDR + 0x0034A)
#define		WAVE_MODEM_B_DEMAP_COEF_4_7_REG_OFFSET					(WAVE_MODEM_B_BASE_ADDR + 0x0034A)

#define		WAVE_MODEM_A_RE_ESTIMATION_MODE_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x0034E)
#define		WAVE_MODEM_B_RE_ESTIMATION_MODE_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x0034E)

#define		WAVE_MODEM_A_ESTIMATION_WEIGHT0_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00352)
#define		WAVE_MODEM_B_ESTIMATION_WEIGHT0_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00352)

#define		WAVE_MODEM_A_ESTIMATION_WEIGHT1_REG_OFFSET				(WAVE_MODEM_A_BASE_ADDR + 0x00356)
#define		WAVE_MODEM_B_ESTIMATION_WEIGHT1_REG_OFFSET				(WAVE_MODEM_B_BASE_ADDR + 0x00356)

#define		WAVE_MODEM_A_INPUT_POWER_REG_OFFSET						(WAVE_MODEM_A_BASE_ADDR + 0x0035A)
#define		WAVE_MODEM_B_INPUT_POWER_REG_OFFSET						(WAVE_MODEM_B_BASE_ADDR + 0x0035A)




/* Interrupt Status Register */
#define		SCH_AC1_TX_COMPLETE_INT									0x1
#define		SCH_AC2_TX_COMPLETE_INT									0x2
#define		SCH_AC3_TX_COMPLETE_INT									0x4
#define		SCH_AC4_TX_COMPLETE_INT									0x8
#define		SCH_AC1_RETX_LIMIT_OVERFLOW_INT							0x10
#define		SCH_AC2_RETX_LIMIT_OVERFLOW_INT							0x20
#define		SCH_AC3_RETX_LIMIT_OVERFLOW_INT							0x40
#define		SCH_AC4_RETX_LIMIT_OVERFLOW_INT							0x80
#define		CCH_AC1_TX_COMPLETE_INT									0x100
#define		CCH_AC2_TX_COMPLETE_INT									0x200
#define		CCH_AC3_TX_COMPLETE_INT									0x400
#define		CCH_AC4_TX_COMPLETE_INT									0x800
#define		CCH_AC1_RETX_LIMIT_OVERFLOW_INT							0x1000
#define		CCH_AC2_RETX_LIMIT_OVERFLOW_INT							0x2000
#define		CCH_AC3_RETX_LIMIT_OVERFLOW_INT							0x4000
#define		CCH_AC4_RETX_LIMIT_OVERFLOW_INT							0x8000
#define		RX_DATA_FRAME_INT										0x10000
#define		RX_MANAGEMENT_FRAME_INT									0x20000
#define		DATA_QUEUE_OVERFLOW_INT									0x40000
#define		MANAGEMENT_QUEUE_OVERFLOW_INT							0x80000
#define		DATA_QUEUE_OVERFLOW_CLEAR_INT							0x100000
#define		MANAGEMENT_QUEUE_OVERFLOW_CLEAR_INT					0x200000
#define		TX_START_OF_EXTRA_QUEUE_INT								0x400000


/* WAVE_MODE_SET_L_REG_OFFSET bit Define */
#define		LOOP_BACK_MODE_BIT										0x40


/* WAVE_MODEM_ETC_REG_OFFSET bit Define */
#define		PHY_COUNTER_CLEAR_BIT									0x8000

/* WAVE_MAC Counter Clear Bit */
#define		MAC_A_COUNTER_CLEAR_BIT									0x40
#define		MAC_B_COUNTER_CLEAR_BIT									0x80


#define	 FND_SIZE	 (0x1000)		/* PAGE 크기의 배수라야 한다. */

#define	 WAVE_DSRC_REG_SIZE	 	(0x80000)		/* PAGE 크기의 배수라야 한다. 512KByte */

/* Define IO macros. */

/* 8 bit access */
#define reg_writeb(reg, data)   ( (*( (volatile U1 *) (reg) ) ) = (U1)(data) )
#define reg_readb(reg)          (  *( (volatile U1 *) (reg) ) )

/* 16 bit access */
#define reg_writew(reg, data)   ( (*( (volatile U2 *) (reg) ) ) = (U2)(data) )
#define reg_readw(reg)          (  *( (volatile U2 *) (reg) ) )

/* 32 bit access */
#define reg_writel(reg, data)  ( (*( (volatile U4 *) (reg) ) ) = (U4)(data) )
#define reg_readl(reg)         (  *( (volatile U4 *) (reg) ) )


